const equipos = [
  { codigo: 'ARG', nombre: 'Argentina', confederacion: 'CONMEBOL', ranking: 1, sedeBase: 'Buenos Aires' },
  { codigo: 'URU', nombre: 'Uruguay', confederacion: 'CONMEBOL', ranking: 2, sedeBase: 'Montevideo' },
  { codigo: 'PAR', nombre: 'Paraguay', confederacion: 'CONMEBOL', ranking: 3, sedeBase: 'Asunción' },
  { codigo: 'BRA', nombre: 'Brasil', confederacion: 'CONMEBOL', ranking: 4, sedeBase: 'San Pablo' },
  { codigo: 'COL', nombre: 'Colombia', confederacion: 'CONMEBOL', ranking: 5, sedeBase: 'Bogotá' },
  { codigo: 'CHI', nombre: 'Chile', confederacion: 'CONMEBOL', ranking: 6, sedeBase: 'Santiago' },
  { codigo: 'ECU', nombre: 'Ecuador', confederacion: 'CONMEBOL', ranking: 7, sedeBase: 'Quito' },
  { codigo: 'PER', nombre: 'Perú', confederacion: 'CONMEBOL', ranking: 8, sedeBase: 'Lima' },
  { codigo: 'ESP', nombre: 'España', confederacion: 'UEFA', ranking: 9, sedeBase: 'Madrid' },
  { codigo: 'POR', nombre: 'Portugal', confederacion: 'UEFA', ranking: 10, sedeBase: 'Lisboa' },
  { codigo: 'MAR', nombre: 'Marruecos', confederacion: 'CAF', ranking: 11, sedeBase: 'Rabat' },
  { codigo: 'FRA', nombre: 'Francia', confederacion: 'UEFA', ranking: 12, sedeBase: 'París' },
  { codigo: 'GER', nombre: 'Alemania', confederacion: 'UEFA', ranking: 13, sedeBase: 'Berlín' },
  { codigo: 'ENG', nombre: 'Inglaterra', confederacion: 'UEFA', ranking: 14, sedeBase: 'Londres' },
  { codigo: 'ITA', nombre: 'Italia', confederacion: 'UEFA', ranking: 15, sedeBase: 'Roma' },
  { codigo: 'NED', nombre: 'Países Bajos', confederacion: 'UEFA', ranking: 16, sedeBase: 'Ámsterdam' },
  { codigo: 'BEL', nombre: 'Bélgica', confederacion: 'UEFA', ranking: 17, sedeBase: 'Bruselas' },
  { codigo: 'CRO', nombre: 'Croacia', confederacion: 'UEFA', ranking: 18, sedeBase: 'Zagreb' },
  { codigo: 'SUI', nombre: 'Suiza', confederacion: 'UEFA', ranking: 19, sedeBase: 'Berna' },
  { codigo: 'DEN', nombre: 'Dinamarca', confederacion: 'UEFA', ranking: 20, sedeBase: 'Copenhague' },
  { codigo: 'POL', nombre: 'Polonia', confederacion: 'UEFA', ranking: 21, sedeBase: 'Varsovia' },
  { codigo: 'SRB', nombre: 'Serbia', confederacion: 'UEFA', ranking: 22, sedeBase: 'Belgrado' },
  { codigo: 'AUT', nombre: 'Austria', confederacion: 'UEFA', ranking: 23, sedeBase: 'Viena' },
  { codigo: 'UKR', nombre: 'Ucrania', confederacion: 'UEFA', ranking: 24, sedeBase: 'Kiev' },
  { codigo: 'WAL', nombre: 'Gales', confederacion: 'UEFA', ranking: 25, sedeBase: 'Cardiff' },
  { codigo: 'SCO', nombre: 'Escocia', confederacion: 'UEFA', ranking: 26, sedeBase: 'Glasgow' },
  { codigo: 'TUR', nombre: 'Turquía', confederacion: 'UEFA', ranking: 27, sedeBase: 'Estambul' },
  { codigo: 'SWE', nombre: 'Suecia', confederacion: 'UEFA', ranking: 28, sedeBase: 'Estocolmo' },
  { codigo: 'CZE', nombre: 'República Checa', confederacion: 'UEFA', ranking: 29, sedeBase: 'Praga' },
  { codigo: 'NOR', nombre: 'Noruega', confederacion: 'UEFA', ranking: 30, sedeBase: 'Oslo' },
  { codigo: 'HUN', nombre: 'Hungría', confederacion: 'UEFA', ranking: 31, sedeBase: 'Budapest' },
  { codigo: 'GRE', nombre: 'Grecia', confederacion: 'UEFA', ranking: 32, sedeBase: 'Atenas' },
  { codigo: 'JPN', nombre: 'Japón', confederacion: 'AFC', ranking: 33, sedeBase: 'Tokio' },
  { codigo: 'KOR', nombre: 'Corea del Sur', confederacion: 'AFC', ranking: 34, sedeBase: 'Seúl' },
  { codigo: 'IRN', nombre: 'Irán', confederacion: 'AFC', ranking: 35, sedeBase: 'Teherán' },
  { codigo: 'KSA', nombre: 'Arabia Saudita', confederacion: 'AFC', ranking: 36, sedeBase: 'Riad' },
  { codigo: 'AUS', nombre: 'Australia', confederacion: 'AFC', ranking: 37, sedeBase: 'Sídney' },
  { codigo: 'QAT', nombre: 'Catar', confederacion: 'AFC', ranking: 38, sedeBase: 'Doha' },
  { codigo: 'IRQ', nombre: 'Irak', confederacion: 'AFC', ranking: 39, sedeBase: 'Bagdad' },
  { codigo: 'UZB', nombre: 'Uzbekistán', confederacion: 'AFC', ranking: 40, sedeBase: 'Taskent' },
  { codigo: 'JOR', nombre: 'Jordania', confederacion: 'AFC', ranking: 41, sedeBase: 'Amán' },
  { codigo: 'UAE', nombre: 'Emiratos Árabes Unidos', confederacion: 'AFC', ranking: 42, sedeBase: 'Abu Dabi' },
  { codigo: 'SEN', nombre: 'Senegal', confederacion: 'CAF', ranking: 43, sedeBase: 'Dakar' },
  { codigo: 'NGA', nombre: 'Nigeria', confederacion: 'CAF', ranking: 44, sedeBase: 'Abuya' },
  { codigo: 'EGY', nombre: 'Egipto', confederacion: 'CAF', ranking: 45, sedeBase: 'El Cairo' },
  { codigo: 'ALG', nombre: 'Argelia', confederacion: 'CAF', ranking: 46, sedeBase: 'Argel' },
  { codigo: 'TUN', nombre: 'Túnez', confederacion: 'CAF', ranking: 47, sedeBase: 'Túnez' },
  { codigo: 'CMR', nombre: 'Camerún', confederacion: 'CAF', ranking: 48, sedeBase: 'Yaundé' },
  { codigo: 'GHA', nombre: 'Ghana', confederacion: 'CAF', ranking: 49, sedeBase: 'Acra' },
  { codigo: 'CIV', nombre: 'Costa de Marfil', confederacion: 'CAF', ranking: 50, sedeBase: 'Abiyán' },
  { codigo: 'RSA', nombre: 'Sudáfrica', confederacion: 'CAF', ranking: 51, sedeBase: 'Johannesburgo' },
  { codigo: 'MLI', nombre: 'Mali', confederacion: 'CAF', ranking: 52, sedeBase: 'Bamako' },
  { codigo: 'MEX', nombre: 'México', confederacion: 'CONCACAF', ranking: 53, sedeBase: 'Ciudad de México' },
  { codigo: 'USA', nombre: 'Estados Unidos', confederacion: 'CONCACAF', ranking: 54, sedeBase: 'Nueva York' },
  { codigo: 'CAN', nombre: 'Canadá', confederacion: 'CONCACAF', ranking: 55, sedeBase: 'Toronto' },
  { codigo: 'CRC', nombre: 'Costa Rica', confederacion: 'CONCACAF', ranking: 56, sedeBase: 'San José' },
  { codigo: 'JAM', nombre: 'Jamaica', confederacion: 'CONCACAF', ranking: 57, sedeBase: 'Kingston' },
  { codigo: 'PAN', nombre: 'Panamá', confederacion: 'CONCACAF', ranking: 58, sedeBase: 'Panamá' },
  { codigo: 'HON', nombre: 'Honduras', confederacion: 'CONCACAF', ranking: 59, sedeBase: 'Tegucigalpa' },
  { codigo: 'NZL', nombre: 'Nueva Zelanda', confederacion: 'OFC', ranking: 60, sedeBase: 'Auckland' },
  { codigo: 'VEN', nombre: 'Venezuela', confederacion: 'CONMEBOL', ranking: 61, sedeBase: 'Caracas' },
  { codigo: 'BOL', nombre: 'Bolivia', confederacion: 'CONMEBOL', ranking: 62, sedeBase: 'La Paz' },
  { codigo: 'SVK', nombre: 'Eslovaquia', confederacion: 'UEFA', ranking: 63, sedeBase: 'Bratislava' },
  { codigo: 'FIN', nombre: 'Finlandia', confederacion: 'UEFA', ranking: 64, sedeBase: 'Helsinki' },
];