/* global use, db */
// MongoDB Playground
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.

// The current database to use.
use("fixture2030");

// carga de jugadores - hasta linea 76


db.jugadores.deleteMany({});  //eliminamos todo antes de cargar para evitar duplicados
db.jugadores.insertMany([
  { nombre: "Simone", apellido: "Suzuki Boateng", dorsal: 29, equipo: "AUS", posicion: "Portero" },
  { nombre: "Emiliano", apellido: "Wozniak Gómez", dorsal: 4, equipo: "URU", posicion: "Defensa" },
  { nombre: "Ryan", apellido: "Sánchez", dorsal: 72, equipo: "ALG", posicion: "Delantero" },
  { nombre: "Charlie", apellido: "Tanaka", dorsal: 1, equipo: "GHA", posicion: "Delantero" },
  { nombre: "Sung-min", apellido: "Evans", dorsal: 98, equipo: "RUS", posicion: "Portero" },
  { nombre: "Alessandro", apellido: "Johansson", dorsal: 45, equipo: "AUT", posicion: "Portero" },
  { nombre: "Pavel", apellido: "Olsson", dorsal: 11, equipo: "NOR", posicion: "Centrocampista" },
  { nombre: "Mathieu", apellido: "Santos", dorsal: 85, equipo: "ECU", posicion: "Centrocampista" },
  { nombre: "Marco", apellido: "Romano", dorsal: 49, equipo: "SWE", posicion: "Delantero" },
  { nombre: "Magnus", apellido: "Andersson", dorsal: 27, equipo: "POL", posicion: "Portero" },
  { nombre: "Louis", apellido: "Boateng", dorsal: 21, equipo: "CHN", posicion: "Delantero" },
  { nombre: "Youssef", apellido: "Thomas", dorsal: 88, equipo: "IRL", posicion: "Portero" },
  { nombre: "Daniel", apellido: "Kim", dorsal: 52, equipo: "POL", posicion: "Portero" },
  { nombre: "Jack", apellido: "Kim", dorsal: 28, equipo: "COD", posicion: "Delantero" },
  { nombre: "Pavel", apellido: "Meyer Asante", dorsal: 96, equipo: "AUT", posicion: "Delantero" },
  { nombre: "Michal", apellido: "Meyer", dorsal: 66, equipo: "COD", posicion: "Portero" },
  { nombre: "Pedro", apellido: "Schulz", dorsal: 81, equipo: "GHA", posicion: "Delantero" },
  { nombre: "Javier", apellido: "Morozov", dorsal: 68, equipo: "SUI", posicion: "Portero" },
  { nombre: "Davide", apellido: "Gutierrez", dorsal: 97, equipo: "POL", posicion: "Centrocampista" },
  { nombre: "Simone", apellido: "Dubois", dorsal: 59, equipo: "ARG", posicion: "Centrocampista" },
  { nombre: "Cem", apellido: "Dogan", dorsal: 14, equipo: "SRB", posicion: "Defensa" },
  { nombre: "Niklas", apellido: "Lefebvre", dorsal: 70, equipo: "ARG", posicion: "Centrocampista" },
  { nombre: "Emre", apellido: "Karlsson Kato", dorsal: 31, equipo: "POR", posicion: "Defensa" },
  { nombre: "Marco", apellido: "Celik Ferreira", dorsal: 98, equipo: "KOR", posicion: "Defensa" },
  { nombre: "Ali", apellido: "Moreau", dorsal: 34, equipo: "KSA", posicion: "Defensa" },
  { nombre: "Joaquín", apellido: "Johnson", dorsal: 92, equipo: "WAL", posicion: "Delantero" },
  { nombre: "Lars", apellido: "Flores", dorsal: 58, equipo: "JPN", posicion: "Defensa" },
  { nombre: "Thomas", apellido: "Martínez Walker", dorsal: 76, equipo: "PER", posicion: "Portero" },
  { nombre: "Pablo", apellido: "Pereira", dorsal: 30, equipo: "NED", posicion: "Portero" },
  { nombre: "Joon-ho", apellido: "Mensah Tanaka", dorsal: 86, equipo: "CIV", posicion: "Defensa" },
  { nombre: "Joaquín", apellido: "Kaya Boateng", dorsal: 61, equipo: "JAM", posicion: "Defensa" },
  { nombre: "Francesco", apellido: "Petrov Andersson", dorsal: 55, equipo: "JAM", posicion: "Delantero" },
  { nombre: "Miguel", apellido: "Romano", dorsal: 8, equipo: "PAN", posicion: "Centrocampista" },
  { nombre: "Leonardo", apellido: "Muller", dorsal: 69, equipo: "UAE", posicion: "Defensa" },
  { nombre: "Wojciech", apellido: "Fedorov", dorsal: 32, equipo: "BEL", posicion: "Delantero" },
  { nombre: "Antonio", apellido: "Chavez Fernández", dorsal: 12, equipo: "PAR", posicion: "Defensa" },
  { nombre: "Krzysztof", apellido: "Wilson", dorsal: 52, equipo: "POR", posicion: "Defensa" },
  { nombre: "Emil", apellido: "Gustafsson Agyeman", dorsal: 59, equipo: "DEN", posicion: "Delantero" },
  { nombre: "Hüseyin", apellido: "Nakamura", dorsal: 28, equipo: "POR", posicion: "Portero" },
  { nombre: "Min-jun", apellido: "Demir Arslan", dorsal: 68, equipo: "GHA", posicion: "Portero" },
  { nombre: "Alexis", apellido: "Vincent Ferreira", dorsal: 77, equipo: "NED", posicion: "Defensa" },
  { nombre: "Tomasz", apellido: "Asante Silva", dorsal: 80, equipo: "CRO", posicion: "Delantero" },
  { nombre: "Esteban", apellido: "Adjei", dorsal: 27, equipo: "SCO", posicion: "Defensa" },
  { nombre: "Mohamed", apellido: "Kobayashi", dorsal: 59, equipo: "SCO", posicion: "Portero" },
  { nombre: "Santiago", apellido: "Romano", dorsal: 10, equipo: "CHI", posicion: "Centrocampista" },
  { nombre: "Maximilian", apellido: "Ferreira", dorsal: 32, equipo: "CZE", posicion: "Centrocampista" },
  { nombre: "Jean", apellido: "Ramos", dorsal: 91, equipo: "SRB", posicion: "Portero" },
  { nombre: "Haruto", apellido: "Colombo", dorsal: 18, equipo: "AUT", posicion: "Portero" },
  { nombre: "Leonardo", apellido: "Schulz", dorsal: 35, equipo: "DEN", posicion: "Defensa" },
  { nombre: "Sung-min", apellido: "Agyeman", dorsal: 65, equipo: "CIV", posicion: "Centrocampista" },
  { nombre: "Miguel", apellido: "Wozniak Suzuki", dorsal: 6, equipo: "ARG", posicion: "Centrocampista" },
  { nombre: "Maximilian", apellido: "Agyeman", dorsal: 21, equipo: "QAT", posicion: "Delantero" },
  { nombre: "Santiago", apellido: "Hoffmann Ramos", dorsal: 5, equipo: "CZE", posicion: "Defensa" },
  { nombre: "Dmitri", apellido: "Kato Nilsson", dorsal: 6, equipo: "GRE", posicion: "Defensa" },
  { nombre: "Samuel", apellido: "Andersson", dorsal: 72, equipo: "JAM", posicion: "Defensa" },
  { nombre: "Kwame", apellido: "Fontaine", dorsal: 53, equipo: "FRA", posicion: "Defensa" },
  { nombre: "Hyun-woo", apellido: "Lewandowski", dorsal: 86, equipo: "VEN", posicion: "Centrocampista" },
  { nombre: "Jean", apellido: "Ricci", dorsal: 49, equipo: "GER", posicion: "Delantero" },
  { nombre: "Charlie", apellido: "Kuznetsov", dorsal: 45, equipo: "WAL", posicion: "Defensa" },
  { nombre: "Thomas", apellido: "Faure Wojcik", dorsal: 43, equipo: "SWE", posicion: "Portero" },
  { nombre: "Takashi", apellido: "Alvarez", dorsal: 52, equipo: "UKR", posicion: "Portero" },
  { nombre: "Davide", apellido: "Adjei", dorsal: 23, equipo: "AUT", posicion: "Portero" },
  { nombre: "Leonardo", apellido: "Jang", dorsal: 94, equipo: "SCO", posicion: "Delantero" },
  { nombre: "Alexis", apellido: "Muller Osei", dorsal: 6, equipo: "IRN", posicion: "Portero" },
  { nombre: "Esteban", apellido: "Gutierrez", dorsal: 88, equipo: "ALG", posicion: "Centrocampista" },
  { nombre: "Dmitri", apellido: "Jung Kim", dorsal: 85, equipo: "JPN", posicion: "Centrocampista" },
  { nombre: "Onur", apellido: "Kaminski", dorsal: 42, equipo: "PAN", posicion: "Centrocampista" },
  { nombre: "Felix", apellido: "Persson", dorsal: 87, equipo: "CMR", posicion: "Centrocampista" },
  { nombre: "Tomasz", apellido: "González", dorsal: 39, equipo: "DEN", posicion: "Defensa" },
  { nombre: "Dmitri", apellido: "Park", dorsal: 60, equipo: "QAT", posicion: "Delantero" },
  { nombre: "Jack", apellido: "Girard", dorsal: 85, equipo: "CRO", posicion: "Centrocampista" },
  { nombre: "Cristian", apellido: "Kang", dorsal: 12, equipo: "PAR", posicion: "Centrocampista" },
  { nombre: "Thomas", apellido: "Becker", dorsal: 4, equipo: "ENG", posicion: "Defensa" },
  { nombre: "Ali", apellido: "Ribeiro", dorsal: 59, equipo: "HON", posicion: "Defensa" },
  { nombre: "Viktor", apellido: "Boateng", dorsal: 19, equipo: "ARG", posicion: "Portero" },
  { nombre: "Wojciech", apellido: "Flores", dorsal: 60, equipo: "ITA", posicion: "Defensa" },
  { nombre: "Lukas", apellido: "Fedorov", dorsal: 86, equipo: "SCO", posicion: "Delantero" },
  { nombre: "Onur", apellido: "Volkov", dorsal: 21, equipo: "NZL", posicion: "Delantero" },
  { nombre: "Ibrahim", apellido: "Suzuki", dorsal: 99, equipo: "CIV", posicion: "Defensa" },
  { nombre: "Hiroshi", apellido: "Ito", dorsal: 31, equipo: "POL", posicion: "Centrocampista" },
  { nombre: "Seo-jun", apellido: "Rossi", dorsal: 18, equipo: "SEN", posicion: "Defensa" },
  { nombre: "Viktor", apellido: "Wilson", dorsal: 9, equipo: "HON", posicion: "Delantero" },
  { nombre: "Joon-ho", apellido: "Zielinski", dorsal: 8, equipo: "COL", posicion: "Delantero" },
  { nombre: "Axel", apellido: "Martínez", dorsal: 98, equipo: "HUN", posicion: "Delantero" },
  { nombre: "Mateo", apellido: "Kobayashi", dorsal: 97, equipo: "ISL", posicion: "Delantero" },
  { nombre: "Vicente", apellido: "Ramos", dorsal: 78, equipo: "PER", posicion: "Delantero" },
  { nombre: "Charlie", apellido: "Celik", dorsal: 4, equipo: "ISL", posicion: "Centrocampista" },
  { nombre: "Tomasz", apellido: "Morozov", dorsal: 17, equipo: "FRA", posicion: "Delantero" },
  { nombre: "Gabriel", apellido: "Dabrowski Weber", dorsal: 60, equipo: "TUN", posicion: "Portero" },
  { nombre: "Ibrahim", apellido: "Wilson", dorsal: 59, equipo: "IRL", posicion: "Centrocampista" },
  { nombre: "Emil", apellido: "Szymanski", dorsal: 33, equipo: "CRO", posicion: "Delantero" },
  { nombre: "Martín", apellido: "Souza", dorsal: 45, equipo: "PER", posicion: "Portero" },
  { nombre: "Carlos", apellido: "Asante", dorsal: 26, equipo: "ESP", posicion: "Defensa" },
  { nombre: "Kofi", apellido: "Greco Evans", dorsal: 60, equipo: "SUI", posicion: "Centrocampista" },
  { nombre: "Nicolas", apellido: "Greco", dorsal: 21, equipo: "WAL", posicion: "Portero" },
  { nombre: "Gabriel", apellido: "Olsson", dorsal: 51, equipo: "ALG", posicion: "Portero" },
  { nombre: "Emmanuel", apellido: "Saito Müller", dorsal: 73, equipo: "ENG", posicion: "Centrocampista" },
  { nombre: "Tomás", apellido: "Eriksson", dorsal: 9, equipo: "RUS", posicion: "Portero" },
  { nombre: "Pawel", apellido: "Ricci", dorsal: 56, equipo: "ROU", posicion: "Delantero" },
  { nombre: "Niklas", apellido: "Rivera", dorsal: 84, equipo: "POL", posicion: "Delantero" },
  { nombre: "Boris", apellido: "Darko", dorsal: 42, equipo: "VEN", posicion: "Portero" },
  { nombre: "Takashi", apellido: "Boateng", dorsal: 97, equipo: "CHN", posicion: "Delantero" },
  { nombre: "Jae-hyun", apellido: "Choi Rousseau", dorsal: 63, equipo: "CHI", posicion: "Centrocampista" },
  { nombre: "Ibrahim", apellido: "Suzuki", dorsal: 72, equipo: "BRA", posicion: "Defensa" },
  { nombre: "Luca", apellido: "Kaminski", dorsal: 63, equipo: "PAR", posicion: "Delantero" },
  { nombre: "Emre", apellido: "López", dorsal: 12, equipo: "NOR", posicion: "Defensa" },
  { nombre: "Tomasz", apellido: "Kato", dorsal: 85, equipo: "CZE", posicion: "Delantero" },
  { nombre: "Ignacio", apellido: "Jung", dorsal: 46, equipo: "IRQ", posicion: "Centrocampista" },
  { nombre: "Sota", apellido: "Müller", dorsal: 93, equipo: "EGY", posicion: "Centrocampista" },
  { nombre: "Thomas", apellido: "Vincent", dorsal: 25, equipo: "CHI", posicion: "Delantero" },
  { nombre: "Hiroshi", apellido: "Vargas", dorsal: 77, equipo: "DEN", posicion: "Portero" },
  { nombre: "Mathieu", apellido: "Karlsson", dorsal: 23, equipo: "SRB", posicion: "Portero" },
  { nombre: "Tomás", apellido: "Santos Souza", dorsal: 71, equipo: "NOR", posicion: "Defensa" },
  { nombre: "Emre", apellido: "Fernández Watanabe", dorsal: 61, equipo: "RSA", posicion: "Delantero" },
  { nombre: "Sung-min", apellido: "Souza", dorsal: 33, equipo: "RSA", posicion: "Portero" },
  { nombre: "Javier", apellido: "Ribeiro", dorsal: 74, equipo: "ITA", posicion: "Defensa" },
  { nombre: "Erik", apellido: "Saito", dorsal: 11, equipo: "VEN", posicion: "Portero" },
  { nombre: "Marek", apellido: "Roberts", dorsal: 67, equipo: "HUN", posicion: "Delantero" },
  { nombre: "Sergei", apellido: "Dabrowski", dorsal: 40, equipo: "POR", posicion: "Portero" },
  { nombre: "George", apellido: "Agyeman", dorsal: 85, equipo: "CRO", posicion: "Defensa" },
  { nombre: "Kofi", apellido: "Carvalho", dorsal: 21, equipo: "ARG", posicion: "Delantero" },
  { nombre: "Nikolai", apellido: "Yilmaz", dorsal: 38, equipo: "GER", posicion: "Defensa" },
  { nombre: "Yuto", apellido: "Popov", dorsal: 10, equipo: "ECU", posicion: "Centrocampista" },
  { nombre: "James", apellido: "Ramos", dorsal: 29, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Leon", apellido: "Moreau Kato", dorsal: 77, equipo: "DEN", posicion: "Delantero" },
  { nombre: "Lukas", apellido: "Saito", dorsal: 90, equipo: "PAN", posicion: "Centrocampista" },
  { nombre: "Cem", apellido: "Sidorov", dorsal: 11, equipo: "ENG", posicion: "Delantero" },
  { nombre: "Do-yun", apellido: "Sánchez", dorsal: 12, equipo: "ECU", posicion: "Portero" },
  { nombre: "Ahmed", apellido: "Bonnet", dorsal: 61, equipo: "QAT", posicion: "Centrocampista" },
  { nombre: "Enzo", apellido: "Ivanov", dorsal: 82, equipo: "CIV", posicion: "Portero" },
  { nombre: "Mehmet", apellido: "Kang", dorsal: 42, equipo: "USA", posicion: "Defensa" },
  { nombre: "Joon-ho", apellido: "Aydin", dorsal: 37, equipo: "PAN", posicion: "Portero" },
  { nombre: "Andrei", apellido: "Appiah Park", dorsal: 15, equipo: "PAN", posicion: "Portero" },
  { nombre: "Joaquín", apellido: "Souza", dorsal: 25, equipo: "ROU", posicion: "Delantero" },
  { nombre: "Sergei", apellido: "Brown", dorsal: 35, equipo: "KOR", posicion: "Centrocampista" },
  { nombre: "Alexei", apellido: "Celik", dorsal: 16, equipo: "FRA", posicion: "Defensa" },
  { nombre: "Jean", apellido: "Fernández", dorsal: 71, equipo: "JAM", posicion: "Portero" },
  { nombre: "Thomas", apellido: "Greco", dorsal: 60, equipo: "JPN", posicion: "Defensa" },
  { nombre: "Serkan", apellido: "Yamamoto", dorsal: 66, equipo: "POL", posicion: "Delantero" },
  { nombre: "Hasan", apellido: "Boateng", dorsal: 59, equipo: "MAR", posicion: "Delantero" },
  { nombre: "Julien", apellido: "Alvarez", dorsal: 96, equipo: "AUS", posicion: "Portero" },
  { nombre: "Hiroshi", apellido: "Zielinski", dorsal: 44, equipo: "POL", posicion: "Portero" },
  { nombre: "Kenji", apellido: "Yildiz", dorsal: 20, equipo: "UAE", posicion: "Delantero" },
  { nombre: "Tae-yang", apellido: "Ramos", dorsal: 49, equipo: "IRQ", posicion: "Centrocampista" },
  { nombre: "Julien", apellido: "Owusu", dorsal: 74, equipo: "ISL", posicion: "Defensa" },
  { nombre: "Andrzej", apellido: "Kaya Persson", dorsal: 50, equipo: "SEN", posicion: "Delantero" },
  { nombre: "Ricardo", apellido: "Jung Romano", dorsal: 57, equipo: "MEX", posicion: "Delantero" },
  { nombre: "Diego", apellido: "Kaminski", dorsal: 84, equipo: "SEN", posicion: "Portero" },
  { nombre: "Mehmet", apellido: "Agyeman", dorsal: 44, equipo: "CRC", posicion: "Portero" },
  { nombre: "Joon-ho", apellido: "Ortiz", dorsal: 49, equipo: "SCO", posicion: "Delantero" },
  { nombre: "Joaquín", apellido: "Ferreira Mensah", dorsal: 81, equipo: "DEN", posicion: "Defensa" },
  { nombre: "Alessandro", apellido: "Romano", dorsal: 98, equipo: "MEX", posicion: "Delantero" },
  { nombre: "Nicolas", apellido: "Pérez", dorsal: 6, equipo: "IRL", posicion: "Portero" },
  { nombre: "Sora", apellido: "Petrov", dorsal: 19, equipo: "VEN", posicion: "Delantero" },
  { nombre: "Enzo", apellido: "Rossi", dorsal: 79, equipo: "HUN", posicion: "Defensa" },
  { nombre: "Serkan", apellido: "Wagner", dorsal: 30, equipo: "CHN", posicion: "Centrocampista" },
  { nombre: "Pavel", apellido: "García", dorsal: 60, equipo: "DEN", posicion: "Defensa" },
  { nombre: "Pablo", apellido: "Jang", dorsal: 76, equipo: "SRB", posicion: "Delantero" },
  { nombre: "Joseph", apellido: "Saito", dorsal: 26, equipo: "ISL", posicion: "Delantero" },
  { nombre: "Leonardo", apellido: "Johansson", dorsal: 74, equipo: "NOR", posicion: "Centrocampista" },
  { nombre: "Nicolás", apellido: "Nowak", dorsal: 36, equipo: "BRA", posicion: "Portero" },
  { nombre: "Serkan", apellido: "Ito", dorsal: 30, equipo: "GRE", posicion: "Defensa" },
  { nombre: "Julien", apellido: "Meyer", dorsal: 81, equipo: "MEX", posicion: "Portero" },
  { nombre: "Yuki", apellido: "Gómez", dorsal: 75, equipo: "ROU", posicion: "Defensa" },
  { nombre: "Alessandro", apellido: "Choi", dorsal: 96, equipo: "HON", posicion: "Defensa" },
  { nombre: "William", apellido: "Chavez Nilsson", dorsal: 68, equipo: "POL", posicion: "Defensa" },
  { nombre: "David", apellido: "Sahin", dorsal: 38, equipo: "RUS", posicion: "Portero" },
  { nombre: "Boris", apellido: "Wagner", dorsal: 97, equipo: "PER", posicion: "Delantero" },
  { nombre: "Magnus", apellido: "Nowak Fernández", dorsal: 34, equipo: "JPN", posicion: "Delantero" },
  { nombre: "Henrik", apellido: "Agyeman", dorsal: 75, equipo: "HUN", posicion: "Centrocampista" },
  { nombre: "Leonardo", apellido: "Yilmaz", dorsal: 4, equipo: "IRL", posicion: "Defensa" },
  { nombre: "Javier", apellido: "Fedorov", dorsal: 90, equipo: "SRB", posicion: "Delantero" },
  { nombre: "Davide", apellido: "Díaz Saito", dorsal: 64, equipo: "CAN", posicion: "Portero" },
  { nombre: "Kwame", apellido: "Weber", dorsal: 50, equipo: "IRQ", posicion: "Centrocampista" },
  { nombre: "Joaquín", apellido: "Schulz", dorsal: 54, equipo: "MEX", posicion: "Delantero" },
  { nombre: "Krzysztof", apellido: "Tanaka", dorsal: 5, equipo: "CZE", posicion: "Defensa" },
  { nombre: "Sergei", apellido: "Mensah", dorsal: 47, equipo: "MEX", posicion: "Centrocampista" },
  { nombre: "Emiliano", apellido: "Johansson", dorsal: 8, equipo: "CRC", posicion: "Centrocampista" },
  { nombre: "Julien", apellido: "Popov", dorsal: 12, equipo: "CHI", posicion: "Portero" },
  { nombre: "Pedro", apellido: "Boateng", dorsal: 17, equipo: "COL", posicion: "Portero" },
  { nombre: "George", apellido: "White", dorsal: 43, equipo: "MAR", posicion: "Portero" },
  { nombre: "Hiroshi", apellido: "Becker", dorsal: 17, equipo: "SUI", posicion: "Defensa" },
  { nombre: "Simone", apellido: "Sánchez", dorsal: 17, equipo: "BRA", posicion: "Centrocampista" },
  { nombre: "Kwame", apellido: "López", dorsal: 23, equipo: "AUT", posicion: "Portero" },
  { nombre: "Felix", apellido: "Vargas", dorsal: 15, equipo: "NED", posicion: "Delantero" },
  { nombre: "Vladimir", apellido: "Torres", dorsal: 76, equipo: "USA", posicion: "Delantero" },
  { nombre: "Cem", apellido: "Santos", dorsal: 94, equipo: "SRB", posicion: "Delantero" },
  { nombre: "Rafael", apellido: "Demir Wojcik", dorsal: 55, equipo: "USA", posicion: "Delantero" },
  { nombre: "Sergei", apellido: "Rossi Park", dorsal: 78, equipo: "MAR", posicion: "Portero" },
  { nombre: "Felix", apellido: "Choi", dorsal: 49, equipo: "NOR", posicion: "Delantero" },
  { nombre: "Onur", apellido: "Romano", dorsal: 90, equipo: "CAN", posicion: "Defensa" },
  { nombre: "Dmitri", apellido: "Walker", dorsal: 53, equipo: "RUS", posicion: "Delantero" },
  { nombre: "Michal", apellido: "Bianchi", dorsal: 41, equipo: "KSA", posicion: "Centrocampista" },
  { nombre: "David", apellido: "Schulz", dorsal: 88, equipo: "NZL", posicion: "Portero" },
  { nombre: "Alessandro", apellido: "Esposito", dorsal: 56, equipo: "MEX", posicion: "Centrocampista" },
  { nombre: "Maximilian", apellido: "Jung", dorsal: 86, equipo: "JPN", posicion: "Delantero" },
  { nombre: "Erik", apellido: "Wozniak", dorsal: 93, equipo: "ITA", posicion: "Centrocampista" },
  { nombre: "Yuki", apellido: "Dogan", dorsal: 28, equipo: "SEN", posicion: "Delantero" },
  { nombre: "Thomas", apellido: "Lim", dorsal: 72, equipo: "CZE", posicion: "Portero" },
  { nombre: "Takashi", apellido: "Dabrowski", dorsal: 72, equipo: "FRA", posicion: "Centrocampista" },
  { nombre: "Rafael", apellido: "Yoshida", dorsal: 44, equipo: "TUR", posicion: "Portero" },
  { nombre: "Enzo", apellido: "Wojcik", dorsal: 9, equipo: "MAR", posicion: "Portero" },
  { nombre: "Alessandro", apellido: "Evans", dorsal: 49, equipo: "HON", posicion: "Delantero" },
  { nombre: "Sung-min", apellido: "Yoshida", dorsal: 93, equipo: "IRL", posicion: "Portero" },
  { nombre: "Miguel", apellido: "Oliveira", dorsal: 87, equipo: "CRO", posicion: "Centrocampista" },
  { nombre: "Sergei", apellido: "Celik", dorsal: 78, equipo: "QAT", posicion: "Delantero" },
  { nombre: "Youssef", apellido: "Torres", dorsal: 15, equipo: "TUR", posicion: "Delantero" },
  { nombre: "Simone", apellido: "Celik", dorsal: 68, equipo: "WAL", posicion: "Portero" },
  { nombre: "Charlie", apellido: "Costa", dorsal: 1, equipo: "COL", posicion: "Centrocampista" },
  { nombre: "Jack", apellido: "Osei", dorsal: 38, equipo: "IRL", posicion: "Portero" },
  { nombre: "Mateo", apellido: "Petrov", dorsal: 23, equipo: "KOR", posicion: "Delantero" },
  { nombre: "Tomás", apellido: "Arslan", dorsal: 72, equipo: "GRE", posicion: "Portero" },
  { nombre: "Jakub", apellido: "Silva", dorsal: 56, equipo: "ESP", posicion: "Delantero" },
  { nombre: "Daniel", apellido: "Dabrowski", dorsal: 74, equipo: "PAN", posicion: "Delantero" },
  { nombre: "Ryo", apellido: "Martínez Choi", dorsal: 22, equipo: "IRQ", posicion: "Centrocampista" },
  { nombre: "Matteo", apellido: "Ricci", dorsal: 32, equipo: "IRN", posicion: "Delantero" },
  { nombre: "Felipe", apellido: "Yoshida Cho", dorsal: 29, equipo: "UKR", posicion: "Defensa" },
  { nombre: "Daniel", apellido: "Greco", dorsal: 68, equipo: "EGY", posicion: "Centrocampista" },
  { nombre: "Woo-jin", apellido: "Becker", dorsal: 31, equipo: "USA", posicion: "Defensa" },
  { nombre: "David", apellido: "Schulz", dorsal: 98, equipo: "BEL", posicion: "Defensa" },
  { nombre: "Burak", apellido: "Volkov", dorsal: 88, equipo: "IRL", posicion: "Centrocampista" },
  { nombre: "Erik", apellido: "Yilmaz", dorsal: 57, equipo: "SRB", posicion: "Centrocampista" },
  { nombre: "Andrés", apellido: "Ribeiro", dorsal: 40, equipo: "CHN", posicion: "Delantero" },
  { nombre: "Ricardo", apellido: "Ito Carvalho", dorsal: 83, equipo: "URU", posicion: "Delantero" },
  { nombre: "Oleg", apellido: "Silva", dorsal: 58, equipo: "EGY", posicion: "Centrocampista" },
  { nombre: "Ali", apellido: "Pereira", dorsal: 58, equipo: "USA", posicion: "Centrocampista" },
  { nombre: "Luca", apellido: "Bonnet", dorsal: 6, equipo: "VEN", posicion: "Delantero" },
  { nombre: "Alexei", apellido: "Dubois", dorsal: 47, equipo: "CZE", posicion: "Centrocampista" },
  { nombre: "Axel", apellido: "Cho", dorsal: 87, equipo: "ITA", posicion: "Centrocampista" },
  { nombre: "Javier", apellido: "Svensson", dorsal: 37, equipo: "SUI", posicion: "Defensa" },
  { nombre: "Hyun-woo", apellido: "Wagner Lim", dorsal: 40, equipo: "CRC", posicion: "Defensa" },
  { nombre: "Luca", apellido: "Olsson", dorsal: 83, equipo: "UKR", posicion: "Defensa" },
  { nombre: "Felipe", apellido: "Wozniak Alvarez", dorsal: 47, equipo: "ESP", posicion: "Centrocampista" },
  { nombre: "Yuki", apellido: "Wilson", dorsal: 44, equipo: "CIV", posicion: "Defensa" },
  { nombre: "Thomas", apellido: "Schulz", dorsal: 10, equipo: "NOR", posicion: "Portero" },
  { nombre: "Onur", apellido: "Vargas", dorsal: 5, equipo: "RUS", posicion: "Defensa" },
  { nombre: "Oskar", apellido: "Rousseau", dorsal: 89, equipo: "NGA", posicion: "Delantero" },
  { nombre: "Juan", apellido: "Mensah", dorsal: 57, equipo: "DEN", posicion: "Delantero" },
  { nombre: "Ryan", apellido: "Yoshida", dorsal: 61, equipo: "EGY", posicion: "Centrocampista" },
  { nombre: "Alexei", apellido: "Watanabe", dorsal: 49, equipo: "HON", posicion: "Defensa" },
  { nombre: "William", apellido: "Meyer", dorsal: 33, equipo: "ITA", posicion: "Delantero" },
  { nombre: "Lars", apellido: "Colombo", dorsal: 92, equipo: "JPN", posicion: "Centrocampista" },
  { nombre: "Luca", apellido: "Nkrumah", dorsal: 58, equipo: "MAR", posicion: "Delantero" },
  { nombre: "Alessandro", apellido: "Thomas", dorsal: 58, equipo: "TUR", posicion: "Portero" },
  { nombre: "Marek", apellido: "Arslan Larsson", dorsal: 31, equipo: "ISL", posicion: "Portero" },
  { nombre: "Lars", apellido: "Lee", dorsal: 13, equipo: "UKR", posicion: "Defensa" },
  { nombre: "Paul", apellido: "Yilmaz Meyer", dorsal: 98, equipo: "NZL", posicion: "Delantero" },
  { nombre: "Mateo", apellido: "López", dorsal: 33, equipo: "CHI", posicion: "Defensa" },
  { nombre: "Ignacio", apellido: "Ito", dorsal: 31, equipo: "SRB", posicion: "Portero" },
  { nombre: "Pedro", apellido: "Kuznetsov", dorsal: 9, equipo: "CAN", posicion: "Delantero" },
  { nombre: "Vicente", apellido: "Torres Owusu", dorsal: 92, equipo: "MAR", posicion: "Centrocampista" },
  { nombre: "Grzegorz", apellido: "Andersson Owusu", dorsal: 74, equipo: "HON", posicion: "Defensa" },
  { nombre: "Luca", apellido: "Karlsson", dorsal: 9, equipo: "ESP", posicion: "Delantero" },
  { nombre: "Mehmet", apellido: "Gustafsson Larsson", dorsal: 33, equipo: "ESP", posicion: "Centrocampista" },
  { nombre: "Sergio", apellido: "Colombo", dorsal: 99, equipo: "UKR", posicion: "Defensa" },
  { nombre: "Juan", apellido: "Cho", dorsal: 83, equipo: "CMR", posicion: "Delantero" },
  { nombre: "Mustafa", apellido: "Weber", dorsal: 9, equipo: "IRQ", posicion: "Portero" },
  { nombre: "Sora", apellido: "Johnson", dorsal: 6, equipo: "SCO", posicion: "Centrocampista" },
  { nombre: "Cristian", apellido: "Ramos", dorsal: 61, equipo: "SUI", posicion: "Portero" },
  { nombre: "Julien", apellido: "Oliveira", dorsal: 84, equipo: "UKR", posicion: "Centrocampista" },
  { nombre: "Lukas", apellido: "Ivanov", dorsal: 52, equipo: "QAT", posicion: "Delantero" },
  { nombre: "Jae-hyun", apellido: "Ozturk", dorsal: 89, equipo: "COD", posicion: "Centrocampista" },
  { nombre: "Rodrigo", apellido: "Russo", dorsal: 94, equipo: "KSA", posicion: "Portero" },
  { nombre: "Dmitri", apellido: "Rousseau", dorsal: 70, equipo: "NOR", posicion: "Centrocampista" },
  { nombre: "Giovanni", apellido: "Nakamura Kato", dorsal: 58, equipo: "KSA", posicion: "Defensa" },
  { nombre: "Sergei", apellido: "Silva", dorsal: 94, equipo: "GRE", posicion: "Delantero" },
  { nombre: "Hiroshi", apellido: "Costa", dorsal: 10, equipo: "PAN", posicion: "Centrocampista" },
  { nombre: "Cristian", apellido: "Dubois", dorsal: 4, equipo: "MAR", posicion: "Delantero" },
  { nombre: "Fernando", apellido: "Mensah Nilsson", dorsal: 47, equipo: "ISL", posicion: "Portero" },
  { nombre: "Niklas", apellido: "Eriksson", dorsal: 48, equipo: "QAT", posicion: "Portero" },
  { nombre: "Paul", apellido: "Nowak", dorsal: 41, equipo: "SWE", posicion: "Defensa" },
  { nombre: "Davide", apellido: "Vincent Ozturk", dorsal: 67, equipo: "ISL", posicion: "Portero" },
  { nombre: "Mohamed", apellido: "Volkov", dorsal: 28, equipo: "DEN", posicion: "Delantero" },
  { nombre: "William", apellido: "Ribeiro Sokolov", dorsal: 23, equipo: "QAT", posicion: "Portero" },
  { nombre: "Seo-jun", apellido: "Almeida", dorsal: 71, equipo: "NOR", posicion: "Centrocampista" },
  { nombre: "Jean", apellido: "Bonnet", dorsal: 47, equipo: "PER", posicion: "Portero" },
  { nombre: "William", apellido: "Mensah", dorsal: 64, equipo: "FRA", posicion: "Centrocampista" },
  { nombre: "Henrik", apellido: "Fischer", dorsal: 79, equipo: "URU", posicion: "Portero" },
  { nombre: "Yuki", apellido: "Demir", dorsal: 68, equipo: "JAM", posicion: "Delantero" },
  { nombre: "Pablo", apellido: "Lee Ribeiro", dorsal: 58, equipo: "CHN", posicion: "Centrocampista" },
  { nombre: "Felix", apellido: "Rousseau", dorsal: 99, equipo: "KOR", posicion: "Delantero" },
  { nombre: "Cem", apellido: "Costa", dorsal: 16, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Nicolas", apellido: "Roberts", dorsal: 45, equipo: "DEN", posicion: "Portero" },
  { nombre: "Joseph", apellido: "Suzuki", dorsal: 17, equipo: "SRB", posicion: "Portero" },
  { nombre: "Cem", apellido: "Schulz", dorsal: 22, equipo: "RUS", posicion: "Portero" },
  { nombre: "Rafael", apellido: "Agyeman Taylor", dorsal: 99, equipo: "HON", posicion: "Portero" },
  { nombre: "Serkan", apellido: "Ramos", dorsal: 38, equipo: "SRB", posicion: "Delantero" },
  { nombre: "Emmanuel", apellido: "Kowalczyk", dorsal: 39, equipo: "IRQ", posicion: "Portero" },
  { nombre: "Alejandro", apellido: "Zielinski", dorsal: 62, equipo: "CHN", posicion: "Defensa" },
  { nombre: "Sung-min", apellido: "Kim", dorsal: 92, equipo: "SCO", posicion: "Centrocampista" },
  { nombre: "Michal", apellido: "Eriksson Torres", dorsal: 72, equipo: "USA", posicion: "Centrocampista" },
  { nombre: "Kofi", apellido: "Darko", dorsal: 58, equipo: "VEN", posicion: "Defensa" },
  { nombre: "Francesco", apellido: "Svensson Szymanski", dorsal: 32, equipo: "GHA", posicion: "Centrocampista" },
  { nombre: "Min-jun", apellido: "Dubois", dorsal: 64, equipo: "CHN", posicion: "Delantero" },
  { nombre: "Sota", apellido: "Esposito", dorsal: 51, equipo: "IRQ", posicion: "Defensa" },
  { nombre: "Oliver", apellido: "Oliveira", dorsal: 7, equipo: "DEN", posicion: "Delantero" },
  { nombre: "Mehmet", apellido: "García", dorsal: 14, equipo: "IRN", posicion: "Defensa" },
  { nombre: "Mohamed", apellido: "Kowalczyk", dorsal: 47, equipo: "ENG", posicion: "Delantero" },
  { nombre: "Miguel", apellido: "Faure", dorsal: 47, equipo: "DEN", posicion: "Portero" },
  { nombre: "Viktor", apellido: "Tanaka", dorsal: 80, equipo: "JPN", posicion: "Defensa" },
  { nombre: "Francesco", apellido: "Cho", dorsal: 72, equipo: "ROU", posicion: "Defensa" },
  { nombre: "James", apellido: "Wojcik", dorsal: 65, equipo: "ENG", posicion: "Portero" },
  { nombre: "Ricardo", apellido: "Kang Kaya", dorsal: 67, equipo: "IRQ", posicion: "Defensa" },
  { nombre: "Cristian", apellido: "Lee Lefebvre", dorsal: 51, equipo: "SRB", posicion: "Centrocampista" },
  { nombre: "Onur", apellido: "Ortiz", dorsal: 63, equipo: "SRB", posicion: "Delantero" },
  { nombre: "Martín", apellido: "Marino", dorsal: 54, equipo: "WAL", posicion: "Portero" },
  { nombre: "Ali", apellido: "Walker", dorsal: 93, equipo: "ITA", posicion: "Delantero" },
  { nombre: "Louis", apellido: "Persson", dorsal: 19, equipo: "VEN", posicion: "Portero" },
  { nombre: "Simone", apellido: "Sidorov", dorsal: 41, equipo: "HON", posicion: "Defensa" },
  { nombre: "Andrzej", apellido: "Lewandowski", dorsal: 65, equipo: "NZL", posicion: "Portero" },
  { nombre: "Paul", apellido: "Choi", dorsal: 85, equipo: "RSA", posicion: "Delantero" },
  { nombre: "Min-jun", apellido: "Kuznetsov", dorsal: 69, equipo: "RUS", posicion: "Centrocampista" },
  { nombre: "Mohamed", apellido: "Faure", dorsal: 32, equipo: "SWE", posicion: "Centrocampista" },
  { nombre: "Thomas", apellido: "Kobayashi", dorsal: 99, equipo: "DEN", posicion: "Defensa" },
  { nombre: "Emre", apellido: "Lim", dorsal: 72, equipo: "SWE", posicion: "Centrocampista" },
  { nombre: "Lukas", apellido: "Ramos", dorsal: 49, equipo: "CRC", posicion: "Centrocampista" },
  { nombre: "Finn", apellido: "Ito", dorsal: 92, equipo: "CRO", posicion: "Centrocampista" },
  { nombre: "Sergei", apellido: "Demir", dorsal: 28, equipo: "ALG", posicion: "Centrocampista" },
  { nombre: "Youssef", apellido: "Owusu Boateng", dorsal: 7, equipo: "PER", posicion: "Defensa" },
  { nombre: "Miguel", apellido: "Jung Yilmaz", dorsal: 13, equipo: "AUS", posicion: "Portero" },
  { nombre: "Jean", apellido: "Kaya", dorsal: 62, equipo: "ALG", posicion: "Centrocampista" },
  { nombre: "Do-yun", apellido: "Pereira", dorsal: 99, equipo: "URU", posicion: "Defensa" },
  { nombre: "Tomás", apellido: "Díaz", dorsal: 23, equipo: "HON", posicion: "Defensa" },
  { nombre: "Ricardo", apellido: "Nowak", dorsal: 64, equipo: "TUN", posicion: "Centrocampista" },
  { nombre: "Ricardo", apellido: "Ricci Kang", dorsal: 37, equipo: "IRQ", posicion: "Delantero" },
  { nombre: "Jonas", apellido: "Morozov", dorsal: 35, equipo: "EGY", posicion: "Portero" },
  { nombre: "Joon-ho", apellido: "Kuznetsov", dorsal: 83, equipo: "SUI", posicion: "Defensa" },
  { nombre: "Diego", apellido: "Nakamura", dorsal: 73, equipo: "EGY", posicion: "Defensa" },
  { nombre: "Tomasz", apellido: "Torres", dorsal: 42, equipo: "URU", posicion: "Delantero" },
  { nombre: "Francesco", apellido: "Meyer", dorsal: 62, equipo: "IRL", posicion: "Defensa" },
  { nombre: "Mateo", apellido: "Mensah", dorsal: 58, equipo: "POL", posicion: "Centrocampista" },
  { nombre: "Ren", apellido: "García", dorsal: 34, equipo: "ROU", posicion: "Defensa" },
  { nombre: "Alejandro", apellido: "Morozov", dorsal: 40, equipo: "GHA", posicion: "Delantero" },
  { nombre: "Cem", apellido: "Yoshida", dorsal: 89, equipo: "JPN", posicion: "Centrocampista" },
  { nombre: "Henrik", apellido: "Thomas", dorsal: 18, equipo: "RSA", posicion: "Defensa" },
  { nombre: "Andrei", apellido: "Larsson", dorsal: 54, equipo: "NZL", posicion: "Defensa" },
  { nombre: "Samuel", apellido: "Rossi", dorsal: 68, equipo: "UAE", posicion: "Centrocampista" },
  { nombre: "Daniel", apellido: "Marino", dorsal: 8, equipo: "ALG", posicion: "Defensa" },
  { nombre: "Nicolas", apellido: "Rivera", dorsal: 57, equipo: "CAN", posicion: "Defensa" },
  { nombre: "Emre", apellido: "Alvarez Volkov", dorsal: 8, equipo: "IRQ", posicion: "Defensa" },
  { nombre: "Cristian", apellido: "Costa", dorsal: 72, equipo: "CHN", posicion: "Centrocampista" },
  { nombre: "Nicolás", apellido: "González", dorsal: 96, equipo: "CHI", posicion: "Portero" },
  { nombre: "Juan", apellido: "Almeida", dorsal: 70, equipo: "POR", posicion: "Portero" },
  { nombre: "Mehmet", apellido: "Kaminski Rousseau", dorsal: 99, equipo: "AUS", posicion: "Delantero" },
  { nombre: "Lars", apellido: "Persson", dorsal: 58, equipo: "HUN", posicion: "Delantero" },
  { nombre: "Marco", apellido: "Chavez", dorsal: 18, equipo: "TUR", posicion: "Portero" },
  { nombre: "Théo", apellido: "Kowalski", dorsal: 68, equipo: "KOR", posicion: "Defensa" },
  { nombre: "Lucas", apellido: "Kobayashi", dorsal: 60, equipo: "KSA", posicion: "Delantero" },
  { nombre: "Daniel", apellido: "Jang", dorsal: 20, equipo: "SWE", posicion: "Defensa" },
  { nombre: "Simone", apellido: "Szymanski López", dorsal: 31, equipo: "COL", posicion: "Portero" },
  { nombre: "Antonio", apellido: "Volkov", dorsal: 77, equipo: "ITA", posicion: "Defensa" },
  { nombre: "Juan", apellido: "White", dorsal: 70, equipo: "CHI", posicion: "Portero" },
  { nombre: "Paul", apellido: "Yamamoto", dorsal: 30, equipo: "SCO", posicion: "Centrocampista" },
  { nombre: "Kwame", apellido: "Wagner", dorsal: 85, equipo: "PER", posicion: "Delantero" },
  { nombre: "Haruto", apellido: "Bonnet", dorsal: 81, equipo: "KSA", posicion: "Delantero" },
  { nombre: "Pedro", apellido: "Persson", dorsal: 68, equipo: "SCO", posicion: "Delantero" },
  { nombre: "Krzysztof", apellido: "Olsson Vincent", dorsal: 97, equipo: "NZL", posicion: "Defensa" },
  { nombre: "Thomas", apellido: "Wagner", dorsal: 60, equipo: "POR", posicion: "Delantero" },
  { nombre: "Marek", apellido: "Weber", dorsal: 50, equipo: "VEN", posicion: "Centrocampista" },
  { nombre: "Harry", apellido: "Rossi", dorsal: 58, equipo: "CZE", posicion: "Portero" },
  { nombre: "Vicente", apellido: "Muller", dorsal: 7, equipo: "POL", posicion: "Delantero" },
  { nombre: "Carlos", apellido: "Muller", dorsal: 98, equipo: "CHI", posicion: "Delantero" },
  { nombre: "George", apellido: "Kang", dorsal: 39, equipo: "BRA", posicion: "Defensa" },
  { nombre: "Julien", apellido: "Müller", dorsal: 96, equipo: "RSA", posicion: "Defensa" },
  { nombre: "Harry", apellido: "Owusu", dorsal: 71, equipo: "IRL", posicion: "Centrocampista" },
  { nombre: "Emil", apellido: "Johansson", dorsal: 40, equipo: "AUT", posicion: "Centrocampista" },
  { nombre: "Cristian", apellido: "Morozov", dorsal: 13, equipo: "NZL", posicion: "Centrocampista" },
  { nombre: "Harry", apellido: "Lewandowski", dorsal: 6, equipo: "PER", posicion: "Defensa" },
  { nombre: "Martín", apellido: "Zielinski", dorsal: 38, equipo: "SEN", posicion: "Defensa" },
  { nombre: "Joon-ho", apellido: "Boateng", dorsal: 64, equipo: "RUS", posicion: "Centrocampista" },
  { nombre: "Emre", apellido: "Yildiz", dorsal: 59, equipo: "NGA", posicion: "Centrocampista" },
  { nombre: "Louis", apellido: "Ramos Yildiz", dorsal: 24, equipo: "POR", posicion: "Portero" },
  { nombre: "Daniel", apellido: "Oliveira", dorsal: 98, equipo: "ARG", posicion: "Delantero" },
  { nombre: "Paul", apellido: "White", dorsal: 9, equipo: "SEN", posicion: "Portero" },
  { nombre: "Oliver", apellido: "Larsson", dorsal: 8, equipo: "RSA", posicion: "Delantero" },
  { nombre: "Martín", apellido: "Lewandowski Fernández", dorsal: 3, equipo: "SWE", posicion: "Centrocampista" },
  { nombre: "Martín", apellido: "Petrov", dorsal: 23, equipo: "USA", posicion: "Portero" },
  { nombre: "Felipe", apellido: "Faure Vargas", dorsal: 33, equipo: "GRE", posicion: "Centrocampista" },
  { nombre: "Jakub", apellido: "Kowalczyk Kuznetsov", dorsal: 73, equipo: "VEN", posicion: "Defensa" },
  { nombre: "Haruto", apellido: "Rossi", dorsal: 84, equipo: "GER", posicion: "Portero" },
  { nombre: "Tomasz", apellido: "Kaya", dorsal: 8, equipo: "BRA", posicion: "Defensa" },
  { nombre: "Luca", apellido: "Ivanov", dorsal: 83, equipo: "UKR", posicion: "Portero" },
  { nombre: "Ignacio", apellido: "Walker", dorsal: 28, equipo: "NZL", posicion: "Centrocampista" },
  { nombre: "Juan", apellido: "Tanaka", dorsal: 70, equipo: "GER", posicion: "Defensa" },
  { nombre: "Min-jun", apellido: "Taylor Wagner", dorsal: 97, equipo: "CRC", posicion: "Portero" },
  { nombre: "Haruto", apellido: "Owusu", dorsal: 73, equipo: "ISL", posicion: "Centrocampista" },
  { nombre: "Viktor", apellido: "Meyer", dorsal: 89, equipo: "CRO", posicion: "Centrocampista" },
  { nombre: "Miguel", apellido: "White Carvalho", dorsal: 44, equipo: "CRC", posicion: "Centrocampista" },
  { nombre: "Rafael", apellido: "Sokolov", dorsal: 63, equipo: "ECU", posicion: "Centrocampista" },
  { nombre: "Oskar", apellido: "Persson", dorsal: 11, equipo: "NOR", posicion: "Defensa" },
  { nombre: "Pablo", apellido: "Schulz Persson", dorsal: 92, equipo: "SEN", posicion: "Delantero" },
  { nombre: "Seo-jun", apellido: "Esposito", dorsal: 1, equipo: "WAL", posicion: "Delantero" },
  { nombre: "Bjorn", apellido: "Colombo", dorsal: 17, equipo: "URU", posicion: "Defensa" },
  { nombre: "Dmitri", apellido: "Torres", dorsal: 53, equipo: "USA", posicion: "Portero" },
  { nombre: "Matteo", apellido: "Esposito", dorsal: 77, equipo: "IRL", posicion: "Delantero" },
  { nombre: "Diego", apellido: "Gustafsson", dorsal: 11, equipo: "VEN", posicion: "Defensa" },
  { nombre: "Emil", apellido: "Darko", dorsal: 39, equipo: "POL", posicion: "Delantero" },
  { nombre: "Finn", apellido: "Ivanov Suzuki", dorsal: 54, equipo: "SRB", posicion: "Delantero" },
  { nombre: "Daniel", apellido: "Asante", dorsal: 93, equipo: "COD", posicion: "Defensa" },
  { nombre: "Pavel", apellido: "Saito Rodríguez", dorsal: 51, equipo: "UKR", posicion: "Delantero" },
  { nombre: "Joon-ho", apellido: "Petrov", dorsal: 84, equipo: "AUS", posicion: "Centrocampista" },
  { nombre: "Do-yun", apellido: "Johnson", dorsal: 62, equipo: "SCO", posicion: "Defensa" },
  { nombre: "Jakub", apellido: "Yamamoto", dorsal: 95, equipo: "CIV", posicion: "Defensa" },
  { nombre: "Ji-ho", apellido: "Kowalski", dorsal: 47, equipo: "CAN", posicion: "Defensa" },
  { nombre: "Emiliano", apellido: "Sánchez", dorsal: 94, equipo: "CHN", posicion: "Defensa" },
  { nombre: "Alexei", apellido: "Ferreira", dorsal: 53, equipo: "COD", posicion: "Defensa" },
  { nombre: "Ren", apellido: "Schulz", dorsal: 92, equipo: "KSA", posicion: "Delantero" },
  { nombre: "Pablo", apellido: "Demir", dorsal: 75, equipo: "PAN", posicion: "Delantero" },
  { nombre: "Emiliano", apellido: "Karlsson Gutierrez", dorsal: 77, equipo: "CRO", posicion: "Portero" },
  { nombre: "Samuel", apellido: "Andersson", dorsal: 22, equipo: "ENG", posicion: "Delantero" },
  { nombre: "Joon-ho", apellido: "Petrov", dorsal: 14, equipo: "BRA", posicion: "Portero" },
  { nombre: "Ibrahim", apellido: "Flores", dorsal: 72, equipo: "PER", posicion: "Delantero" },
  { nombre: "Lars", apellido: "Arslan", dorsal: 20, equipo: "TUR", posicion: "Portero" },
  { nombre: "Hasan", apellido: "Zielinski Russo", dorsal: 15, equipo: "MAR", posicion: "Centrocampista" },
  { nombre: "Yuki", apellido: "Brown", dorsal: 67, equipo: "RSA", posicion: "Centrocampista" },
  { nombre: "Ali", apellido: "Sokolov Lee", dorsal: 9, equipo: "SRB", posicion: "Portero" },
  { nombre: "Davide", apellido: "Yoon Ricci", dorsal: 87, equipo: "NGA", posicion: "Defensa" },
  { nombre: "Rodrigo", apellido: "Dubois", dorsal: 43, equipo: "KSA", posicion: "Delantero" },
  { nombre: "Ryan", apellido: "Vincent", dorsal: 24, equipo: "IRN", posicion: "Delantero" },
  { nombre: "Rafael", apellido: "Smith", dorsal: 58, equipo: "KSA", posicion: "Delantero" },
  { nombre: "Mateo", apellido: "Brown", dorsal: 36, equipo: "NED", posicion: "Portero" },
  { nombre: "Vicente", apellido: "Choi", dorsal: 26, equipo: "IRQ", posicion: "Portero" },
  { nombre: "Mohamed", apellido: "Yildiz", dorsal: 68, equipo: "SCO", posicion: "Delantero" },
  { nombre: "Piotr", apellido: "Lim", dorsal: 46, equipo: "IRQ", posicion: "Defensa" },
  { nombre: "Haruto", apellido: "Russo", dorsal: 87, equipo: "AUS", posicion: "Centrocampista" },
  { nombre: "Thomas", apellido: "Greco", dorsal: 24, equipo: "CZE", posicion: "Defensa" },
  { nombre: "Alexis", apellido: "Meyer", dorsal: 74, equipo: "ISL", posicion: "Delantero" },
  { nombre: "Antoine", apellido: "Gutierrez", dorsal: 89, equipo: "CMR", posicion: "Defensa" },
  { nombre: "Emre", apellido: "Vincent", dorsal: 41, equipo: "UAE", posicion: "Portero" },
  { nombre: "Anders", apellido: "Celik", dorsal: 18, equipo: "EGY", posicion: "Delantero" },
  { nombre: "Onur", apellido: "Kaminski", dorsal: 88, equipo: "CIV", posicion: "Delantero" },
  { nombre: "Sergei", apellido: "Russo", dorsal: 73, equipo: "FRA", posicion: "Defensa" },
  { nombre: "Ryo", apellido: "Roberts Gutierrez", dorsal: 37, equipo: "NGA", posicion: "Delantero" },
  { nombre: "Burak", apellido: "Marino", dorsal: 74, equipo: "CAN", posicion: "Centrocampista" },
  { nombre: "Emiliano", apellido: "Nilsson", dorsal: 70, equipo: "ENG", posicion: "Delantero" },
  { nombre: "Emiliano", apellido: "Wozniak", dorsal: 14, equipo: "VEN", posicion: "Centrocampista" },
  { nombre: "Fernando", apellido: "Lim", dorsal: 12, equipo: "QAT", posicion: "Portero" },
  { nombre: "Kwame", apellido: "Lim", dorsal: 91, equipo: "KSA", posicion: "Defensa" },
  { nombre: "Paul", apellido: "Brown", dorsal: 8, equipo: "TUR", posicion: "Centrocampista" },
  { nombre: "Vicente", apellido: "Yamamoto", dorsal: 38, equipo: "POL", posicion: "Portero" },
  { nombre: "Jonas", apellido: "Lewandowski", dorsal: 8, equipo: "SWE", posicion: "Defensa" },
  { nombre: "Maximilian", apellido: "Park", dorsal: 32, equipo: "CRC", posicion: "Delantero" },
  { nombre: "Leon", apellido: "Darko", dorsal: 81, equipo: "HON", posicion: "Delantero" },
  { nombre: "Nikolai", apellido: "Esposito Kowalczyk", dorsal: 66, equipo: "SWE", posicion: "Centrocampista" },
  { nombre: "Andrei", apellido: "Choi", dorsal: 75, equipo: "ARG", posicion: "Portero" },
  { nombre: "Pavel", apellido: "Johansson", dorsal: 9, equipo: "CRC", posicion: "Defensa" },
  { nombre: "Grzegorz", apellido: "Aydin", dorsal: 35, equipo: "IRL", posicion: "Centrocampista" },
  { nombre: "Jae-hyun", apellido: "Fischer", dorsal: 73, equipo: "CIV", posicion: "Centrocampista" },
  { nombre: "Pedro", apellido: "Kuznetsov López", dorsal: 16, equipo: "GHA", posicion: "Delantero" },
  { nombre: "Andrei", apellido: "Dabrowski Johnson", dorsal: 89, equipo: "KOR", posicion: "Centrocampista" },
  { nombre: "Jean", apellido: "Suzuki", dorsal: 12, equipo: "ROU", posicion: "Centrocampista" },
  { nombre: "Luca", apellido: "Moreau", dorsal: 7, equipo: "CRC", posicion: "Centrocampista" },
  { nombre: "Ryan", apellido: "Esposito", dorsal: 91, equipo: "MEX", posicion: "Portero" },
  { nombre: "Jack", apellido: "Fischer", dorsal: 76, equipo: "PER", posicion: "Delantero" },
  { nombre: "Santiago", apellido: "Yoon Müller", dorsal: 55, equipo: "KOR", posicion: "Delantero" },
  { nombre: "Pablo", apellido: "Ferrari", dorsal: 94, equipo: "USA", posicion: "Portero" },
  { nombre: "Min-jun", apellido: "Kobayashi", dorsal: 18, equipo: "HUN", posicion: "Defensa" },
  { nombre: "Leon", apellido: "García Moreau", dorsal: 57, equipo: "TUR", posicion: "Defensa" },
  { nombre: "Erik", apellido: "Smirnov", dorsal: 28, equipo: "URU", posicion: "Portero" },
  { nombre: "Paul", apellido: "Svensson", dorsal: 45, equipo: "KSA", posicion: "Centrocampista" },
  { nombre: "Paul", apellido: "Russo", dorsal: 32, equipo: "DEN", posicion: "Portero" },
  { nombre: "Ren", apellido: "Alvarez", dorsal: 25, equipo: "CRC", posicion: "Centrocampista" },
  { nombre: "Miguel", apellido: "Owusu", dorsal: 64, equipo: "ISL", posicion: "Portero" },
  { nombre: "Kofi", apellido: "Ribeiro", dorsal: 68, equipo: "BRA", posicion: "Centrocampista" },
  { nombre: "Seo-jun", apellido: "Szymanski Nilsson", dorsal: 70, equipo: "CMR", posicion: "Delantero" },
  { nombre: "Pablo", apellido: "Ferreira Fernández", dorsal: 34, equipo: "CHI", posicion: "Portero" },
  { nombre: "Alejandro", apellido: "Nowak", dorsal: 65, equipo: "DEN", posicion: "Delantero" },
  { nombre: "Wojciech", apellido: "Russo", dorsal: 82, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Luca", apellido: "Alvarez", dorsal: 27, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Piotr", apellido: "Almeida", dorsal: 40, equipo: "IRN", posicion: "Defensa" },
  { nombre: "Andrés", apellido: "Ivanov", dorsal: 15, equipo: "IRQ", posicion: "Portero" },
  { nombre: "Yuki", apellido: "Bonnet", dorsal: 16, equipo: "BRA", posicion: "Defensa" },
  { nombre: "Santiago", apellido: "Jang", dorsal: 67, equipo: "AUT", posicion: "Defensa" },
  { nombre: "Lars", apellido: "Darko Müller", dorsal: 99, equipo: "FRA", posicion: "Centrocampista" },
  { nombre: "Grzegorz", apellido: "Almeida", dorsal: 34, equipo: "BEL", posicion: "Delantero" },
  { nombre: "Andrei", apellido: "Costa", dorsal: 64, equipo: "NGA", posicion: "Centrocampista" },
  { nombre: "Jean", apellido: "Colombo", dorsal: 74, equipo: "CAN", posicion: "Defensa" },
  { nombre: "Alexis", apellido: "Fernández Boateng", dorsal: 6, equipo: "NZL", posicion: "Centrocampista" },
  { nombre: "Viktor", apellido: "Fontaine", dorsal: 5, equipo: "HON", posicion: "Defensa" },
  { nombre: "Do-yun", apellido: "Lee", dorsal: 35, equipo: "BEL", posicion: "Centrocampista" },
  { nombre: "Thomas", apellido: "Souza", dorsal: 23, equipo: "PER", posicion: "Portero" },
  { nombre: "Michal", apellido: "Morozov Watanabe", dorsal: 40, equipo: "IRL", posicion: "Portero" },
  { nombre: "Andrei", apellido: "Johnson Yamamoto", dorsal: 73, equipo: "SRB", posicion: "Defensa" },
  { nombre: "Oleg", apellido: "Aydin", dorsal: 99, equipo: "ALG", posicion: "Defensa" },
  { nombre: "Erik", apellido: "Kaminski Sánchez", dorsal: 30, equipo: "TUR", posicion: "Portero" },
  { nombre: "Hyun-woo", apellido: "Olsson Kato", dorsal: 14, equipo: "COL", posicion: "Defensa" },
  { nombre: "Pawel", apellido: "Pereira", dorsal: 19, equipo: "SWE", posicion: "Portero" },
  { nombre: "Juan", apellido: "Rivera", dorsal: 53, equipo: "CZE", posicion: "Delantero" },
  { nombre: "Luca", apellido: "Dogan", dorsal: 18, equipo: "CRC", posicion: "Portero" },
  { nombre: "Alejandro", apellido: "Fischer", dorsal: 31, equipo: "NOR", posicion: "Centrocampista" },
  { nombre: "Min-jun", apellido: "Kowalski", dorsal: 90, equipo: "IRL", posicion: "Centrocampista" },
  { nombre: "Nikolai", apellido: "Carvalho", dorsal: 26, equipo: "AUS", posicion: "Portero" },
  { nombre: "Niklas", apellido: "Sokolov Morozov", dorsal: 41, equipo: "JAM", posicion: "Portero" },
  { nombre: "Vicente", apellido: "Taylor", dorsal: 58, equipo: "WAL", posicion: "Delantero" },
  { nombre: "Mohamed", apellido: "Esposito", dorsal: 21, equipo: "SRB", posicion: "Portero" },
  { nombre: "Oliver", apellido: "Choi", dorsal: 19, equipo: "URU", posicion: "Defensa" },
  { nombre: "Anders", apellido: "Oliveira", dorsal: 87, equipo: "SRB", posicion: "Centrocampista" },
  { nombre: "Hugo", apellido: "Kowalczyk Sokolov", dorsal: 72, equipo: "VEN", posicion: "Portero" },
  { nombre: "Oleg", apellido: "Meyer Schmidt", dorsal: 2, equipo: "POR", posicion: "Defensa" },
  { nombre: "Maximilian", apellido: "Wojcik", dorsal: 48, equipo: "CRO", posicion: "Centrocampista" },
  { nombre: "Daniel", apellido: "Almeida Smith", dorsal: 83, equipo: "QAT", posicion: "Defensa" },
  { nombre: "Alessandro", apellido: "Jung", dorsal: 16, equipo: "ENG", posicion: "Delantero" },
  { nombre: "Pedro", apellido: "Petrov", dorsal: 93, equipo: "CRC", posicion: "Delantero" },
  { nombre: "Rafael", apellido: "Dabrowski", dorsal: 23, equipo: "GRE", posicion: "Defensa" },
  { nombre: "Antoine", apellido: "Volkov", dorsal: 20, equipo: "GER", posicion: "Defensa" },
  { nombre: "Sora", apellido: "Demir", dorsal: 8, equipo: "URU", posicion: "Centrocampista" },
  { nombre: "Viktor", apellido: "Johnson Vargas", dorsal: 32, equipo: "ESP", posicion: "Delantero" },
  { nombre: "Anders", apellido: "Celik", dorsal: 45, equipo: "IRL", posicion: "Delantero" },
  { nombre: "Youssef", apellido: "Lee", dorsal: 77, equipo: "PER", posicion: "Portero" },
  { nombre: "Takashi", apellido: "Yilmaz Castro", dorsal: 46, equipo: "ECU", posicion: "Defensa" },
  { nombre: "Antonio", apellido: "Owusu", dorsal: 35, equipo: "POR", posicion: "Defensa" },
  { nombre: "Axel", apellido: "Bonnet", dorsal: 23, equipo: "PAR", posicion: "Centrocampista" },
  { nombre: "Anders", apellido: "Pérez", dorsal: 91, equipo: "GRE", posicion: "Defensa" },
  { nombre: "Julien", apellido: "Aydin", dorsal: 70, equipo: "WAL", posicion: "Defensa" },
  { nombre: "Emre", apellido: "Costa White", dorsal: 78, equipo: "PER", posicion: "Portero" },
  { nombre: "Felipe", apellido: "Jung", dorsal: 79, equipo: "ALG", posicion: "Defensa" },
  { nombre: "Sung-min", apellido: "Park", dorsal: 8, equipo: "ESP", posicion: "Defensa" },
  { nombre: "Leon", apellido: "Vargas", dorsal: 47, equipo: "BEL", posicion: "Centrocampista" },
  { nombre: "Jakub", apellido: "Cho", dorsal: 39, equipo: "IRL", posicion: "Defensa" },
  { nombre: "Jean", apellido: "Ivanov", dorsal: 82, equipo: "CIV", posicion: "Centrocampista" },
  { nombre: "Hugo", apellido: "Johansson", dorsal: 29, equipo: "CMR", posicion: "Delantero" },
  { nombre: "Sota", apellido: "Nakamura", dorsal: 17, equipo: "CMR", posicion: "Portero" },
  { nombre: "Piotr", apellido: "Gómez", dorsal: 24, equipo: "SCO", posicion: "Defensa" },
  { nombre: "Giovanni", apellido: "Wagner", dorsal: 43, equipo: "BEL", posicion: "Defensa" },
  { nombre: "Tae-yang", apellido: "Moreau", dorsal: 82, equipo: "URU", posicion: "Centrocampista" },
  { nombre: "Vladimir", apellido: "Taylor Asante", dorsal: 89, equipo: "NED", posicion: "Centrocampista" },
  { nombre: "David", apellido: "González", dorsal: 7, equipo: "ISL", posicion: "Delantero" },
  { nombre: "Pawel", apellido: "Lewandowski", dorsal: 64, equipo: "HUN", posicion: "Centrocampista" },
  { nombre: "Emiliano", apellido: "Demir", dorsal: 74, equipo: "PER", posicion: "Defensa" },
  { nombre: "Nikolai", apellido: "Gómez Nakamura", dorsal: 3, equipo: "SCO", posicion: "Centrocampista" },
  { nombre: "Giovanni", apellido: "Girard Olsson", dorsal: 21, equipo: "BEL", posicion: "Portero" },
  { nombre: "Jae-hyun", apellido: "Sahin", dorsal: 91, equipo: "FRA", posicion: "Delantero" },
  { nombre: "Nicolas", apellido: "Ivanov", dorsal: 21, equipo: "ITA", posicion: "Portero" },
  { nombre: "Joon-ho", apellido: "Muller", dorsal: 53, equipo: "AUT", posicion: "Centrocampista" },
  { nombre: "Haruto", apellido: "Oliveira", dorsal: 51, equipo: "CIV", posicion: "Defensa" },
  { nombre: "Miguel", apellido: "Dabrowski", dorsal: 12, equipo: "NOR", posicion: "Delantero" },
  { nombre: "William", apellido: "Brown Girard", dorsal: 82, equipo: "NOR", posicion: "Portero" },
  { nombre: "Ali", apellido: "Kato", dorsal: 51, equipo: "NZL", posicion: "Delantero" },
  { nombre: "Mohamed", apellido: "Ramos Gustafsson", dorsal: 24, equipo: "CZE", posicion: "Delantero" },
  { nombre: "Henrik", apellido: "Santos", dorsal: 34, equipo: "QAT", posicion: "Delantero" },
  { nombre: "Mohamed", apellido: "Darko", dorsal: 73, equipo: "POR", posicion: "Defensa" },
  { nombre: "Francesco", apellido: "Jang Chavez", dorsal: 53, equipo: "ECU", posicion: "Portero" },
  { nombre: "Axel", apellido: "Szymanski", dorsal: 69, equipo: "NZL", posicion: "Defensa" },
  { nombre: "Ali", apellido: "Nowak", dorsal: 92, equipo: "GER", posicion: "Defensa" },
  { nombre: "Thomas", apellido: "Volkov", dorsal: 23, equipo: "NGA", posicion: "Defensa" },
  { nombre: "Mathieu", apellido: "Wozniak Rossi", dorsal: 88, equipo: "IRN", posicion: "Defensa" },
  { nombre: "Finn", apellido: "Adjei", dorsal: 41, equipo: "NED", posicion: "Portero" },
  { nombre: "Axel", apellido: "Choi", dorsal: 36, equipo: "IRQ", posicion: "Portero" },
  { nombre: "Esteban", apellido: "Marino", dorsal: 54, equipo: "SEN", posicion: "Defensa" },
  { nombre: "Antonio", apellido: "Romano", dorsal: 37, equipo: "TUR", posicion: "Delantero" },
  { nombre: "Mohamed", apellido: "Celik", dorsal: 74, equipo: "NZL", posicion: "Portero" },
  { nombre: "Hugo", apellido: "Wagner", dorsal: 80, equipo: "PAN", posicion: "Portero" },
  { nombre: "Jakub", apellido: "Jung", dorsal: 89, equipo: "PAR", posicion: "Portero" },
  { nombre: "Ali", apellido: "Larsson", dorsal: 3, equipo: "RUS", posicion: "Centrocampista" },
  { nombre: "Yuki", apellido: "Yildiz", dorsal: 90, equipo: "MEX", posicion: "Defensa" },
  { nombre: "Jonas", apellido: "Smirnov", dorsal: 42, equipo: "POL", posicion: "Delantero" },
  { nombre: "Matteo", apellido: "Wilson", dorsal: 53, equipo: "CIV", posicion: "Centrocampista" },
  { nombre: "Andrés", apellido: "Dubois", dorsal: 9, equipo: "WAL", posicion: "Delantero" },
  { nombre: "Jonas", apellido: "Vargas", dorsal: 73, equipo: "FRA", posicion: "Defensa" },
  { nombre: "Mathieu", apellido: "Johnson", dorsal: 8, equipo: "VEN", posicion: "Portero" },
  { nombre: "Andrei", apellido: "Karlsson Smith", dorsal: 36, equipo: "CZE", posicion: "Delantero" },
  { nombre: "Onur", apellido: "Schmidt", dorsal: 88, equipo: "FRA", posicion: "Defensa" },
  { nombre: "Lars", apellido: "Volkov", dorsal: 23, equipo: "NZL", posicion: "Centrocampista" },
  { nombre: "Tae-yang", apellido: "Adjei", dorsal: 96, equipo: "URU", posicion: "Centrocampista" },
  { nombre: "Rafael", apellido: "Lefebvre", dorsal: 74, equipo: "CHI", posicion: "Defensa" },
  { nombre: "Thomas", apellido: "Darko", dorsal: 84, equipo: "JAM", posicion: "Portero" },
  { nombre: "Santiago", apellido: "Fischer", dorsal: 83, equipo: "CMR", posicion: "Portero" },
  { nombre: "Thomas", apellido: "Kato", dorsal: 92, equipo: "SWE", posicion: "Delantero" },
  { nombre: "Oskar", apellido: "Kuznetsov", dorsal: 33, equipo: "CHI", posicion: "Delantero" },
  { nombre: "Ren", apellido: "Nowak", dorsal: 75, equipo: "USA", posicion: "Portero" },
  { nombre: "Alexis", apellido: "Larsson", dorsal: 72, equipo: "DEN", posicion: "Centrocampista" },
  { nombre: "Leonardo", apellido: "Cho", dorsal: 36, equipo: "IRL", posicion: "Centrocampista" },
  { nombre: "Ibrahim", apellido: "Kobayashi", dorsal: 25, equipo: "SEN", posicion: "Defensa" },
  { nombre: "Andrés", apellido: "Kowalczyk", dorsal: 85, equipo: "SCO", posicion: "Defensa" },
  { nombre: "Gabriel", apellido: "Nakamura", dorsal: 34, equipo: "HON", posicion: "Delantero" },
  { nombre: "Axel", apellido: "Muller", dorsal: 44, equipo: "PER", posicion: "Delantero" },
  { nombre: "Anders", apellido: "Girard", dorsal: 85, equipo: "TUN", posicion: "Centrocampista" },
  { nombre: "Francesco", apellido: "Adjei", dorsal: 93, equipo: "TUN", posicion: "Centrocampista" },
  { nombre: "Matteo", apellido: "Roberts", dorsal: 96, equipo: "WAL", posicion: "Delantero" },
  { nombre: "Joon-ho", apellido: "Nakamura", dorsal: 60, equipo: "JPN", posicion: "Delantero" },
  { nombre: "Miguel", apellido: "Ribeiro", dorsal: 61, equipo: "EGY", posicion: "Portero" },
  { nombre: "Emil", apellido: "Lewandowski", dorsal: 7, equipo: "SEN", posicion: "Defensa" },
  { nombre: "William", apellido: "Kuznetsov", dorsal: 19, equipo: "SCO", posicion: "Defensa" },
  { nombre: "Marco", apellido: "Fontaine", dorsal: 41, equipo: "POR", posicion: "Portero" },
  { nombre: "Nikolai", apellido: "Girard", dorsal: 74, equipo: "GHA", posicion: "Delantero" },
  { nombre: "Matteo", apellido: "Ivanov Dabrowski", dorsal: 52, equipo: "KSA", posicion: "Delantero" },
  { nombre: "Viktor", apellido: "Ortiz Johnson", dorsal: 94, equipo: "CZE", posicion: "Portero" },
  { nombre: "Do-yun", apellido: "Castro", dorsal: 25, equipo: "ESP", posicion: "Portero" },
  { nombre: "Samuel", apellido: "Jang", dorsal: 40, equipo: "KOR", posicion: "Portero" },
  { nombre: "Viktor", apellido: "Kato", dorsal: 22, equipo: "NED", posicion: "Portero" },
  { nombre: "Haruto", apellido: "Popov", dorsal: 94, equipo: "RUS", posicion: "Delantero" },
  { nombre: "Jonas", apellido: "Yildiz", dorsal: 46, equipo: "EGY", posicion: "Defensa" },
  { nombre: "Tomasz", apellido: "Roberts Fischer", dorsal: 28, equipo: "ESP", posicion: "Defensa" },
  { nombre: "Lukas", apellido: "Díaz", dorsal: 49, equipo: "SUI", posicion: "Portero" },
  { nombre: "Pedro", apellido: "Martínez", dorsal: 7, equipo: "CAN", posicion: "Delantero" },
  { nombre: "Sergei", apellido: "Appiah", dorsal: 61, equipo: "SEN", posicion: "Defensa" },
  { nombre: "Santiago", apellido: "Romano", dorsal: 85, equipo: "POL", posicion: "Defensa" },
  { nombre: "Pawel", apellido: "Colombo", dorsal: 66, equipo: "JPN", posicion: "Centrocampista" },
  { nombre: "Davide", apellido: "Ozturk", dorsal: 26, equipo: "ALG", posicion: "Centrocampista" },
  { nombre: "Esteban", apellido: "Johansson", dorsal: 91, equipo: "JAM", posicion: "Centrocampista" },
  { nombre: "Pierre", apellido: "Ozturk Taylor", dorsal: 89, equipo: "RSA", posicion: "Centrocampista" },
  { nombre: "Kwame", apellido: "Ferrari Marino", dorsal: 74, equipo: "COD", posicion: "Defensa" },
  { nombre: "Alessandro", apellido: "Carvalho", dorsal: 93, equipo: "MEX", posicion: "Centrocampista" },
  { nombre: "Ryan", apellido: "Nakamura", dorsal: 34, equipo: "CHN", posicion: "Portero" },
  { nombre: "Antonio", apellido: "Silva", dorsal: 38, equipo: "ROU", posicion: "Centrocampista" },
  { nombre: "Grzegorz", apellido: "Bianchi", dorsal: 98, equipo: "ENG", posicion: "Portero" },
  { nombre: "Paul", apellido: "Girard", dorsal: 43, equipo: "GRE", posicion: "Delantero" },
  { nombre: "Ahmed", apellido: "Esposito", dorsal: 48, equipo: "RUS", posicion: "Defensa" },
  { nombre: "Davide", apellido: "Popov", dorsal: 35, equipo: "ISL", posicion: "Delantero" },
  { nombre: "Pawel", apellido: "Moreau", dorsal: 15, equipo: "KOR", posicion: "Portero" },
  { nombre: "Jean", apellido: "Sahin Sidorov", dorsal: 24, equipo: "HUN", posicion: "Centrocampista" },
  { nombre: "Rafael", apellido: "Fischer", dorsal: 62, equipo: "CIV", posicion: "Portero" },
  { nombre: "Andrzej", apellido: "Almeida", dorsal: 34, equipo: "SCO", posicion: "Portero" },
  { nombre: "Felipe", apellido: "Roberts", dorsal: 86, equipo: "RUS", posicion: "Portero" },
  { nombre: "Dmitri", apellido: "Asante", dorsal: 62, equipo: "TUR", posicion: "Delantero" },
  { nombre: "Erik", apellido: "Souza", dorsal: 2, equipo: "GHA", posicion: "Delantero" },
  { nombre: "Burak", apellido: "Carvalho", dorsal: 97, equipo: "CIV", posicion: "Centrocampista" },
  { nombre: "Kofi", apellido: "Tanaka", dorsal: 7, equipo: "PER", posicion: "Delantero" },
  { nombre: "Tomasz", apellido: "Rossi", dorsal: 59, equipo: "QAT", posicion: "Delantero" },
  { nombre: "Matteo", apellido: "Volkov", dorsal: 41, equipo: "JPN", posicion: "Delantero" },
  { nombre: "Martín", apellido: "Lewandowski Díaz", dorsal: 72, equipo: "ARG", posicion: "Portero" },
  { nombre: "Ren", apellido: "Brown", dorsal: 84, equipo: "IRQ", posicion: "Centrocampista" },
  { nombre: "Magnus", apellido: "Roberts", dorsal: 59, equipo: "UKR", posicion: "Delantero" },
  { nombre: "Magnus", apellido: "Greco", dorsal: 13, equipo: "PER", posicion: "Portero" },
  { nombre: "Sung-min", apellido: "Yamamoto", dorsal: 71, equipo: "CZE", posicion: "Portero" },
  { nombre: "Juan", apellido: "Aydin", dorsal: 18, equipo: "JAM", posicion: "Portero" },
  { nombre: "David", apellido: "Muller", dorsal: 16, equipo: "CRC", posicion: "Defensa" },
  { nombre: "Pavel", apellido: "Muller", dorsal: 92, equipo: "RUS", posicion: "Portero" },
  { nombre: "Marek", apellido: "Schmidt Sokolov", dorsal: 59, equipo: "AUS", posicion: "Delantero" },
  { nombre: "Mateo", apellido: "Oliveira", dorsal: 71, equipo: "IRN", posicion: "Delantero" },
  { nombre: "Alexis", apellido: "Fontaine", dorsal: 89, equipo: "CMR", posicion: "Defensa" },
  { nombre: "Giovanni", apellido: "Park", dorsal: 65, equipo: "ISL", posicion: "Delantero" },
  { nombre: "Samuel", apellido: "Yoon", dorsal: 38, equipo: "UAE", posicion: "Defensa" },
  { nombre: "Paul", apellido: "Torres", dorsal: 39, equipo: "SCO", posicion: "Defensa" },
  { nombre: "William", apellido: "Yamamoto", dorsal: 88, equipo: "TUR", posicion: "Defensa" },
  { nombre: "Théo", apellido: "Park", dorsal: 91, equipo: "CAN", posicion: "Centrocampista" },
  { nombre: "Mustafa", apellido: "Zielinski", dorsal: 87, equipo: "DEN", posicion: "Delantero" },
  { nombre: "Diego", apellido: "Sánchez", dorsal: 49, equipo: "MAR", posicion: "Portero" },
  { nombre: "Andrés", apellido: "Lefebvre", dorsal: 37, equipo: "SUI", posicion: "Defensa" },
  { nombre: "Alejandro", apellido: "Nakamura", dorsal: 27, equipo: "GER", posicion: "Centrocampista" },
  { nombre: "Nikolai", apellido: "Roberts Gustafsson", dorsal: 31, equipo: "DEN", posicion: "Portero" },
  { nombre: "Emil", apellido: "Kim", dorsal: 71, equipo: "ITA", posicion: "Portero" },
  { nombre: "Joseph", apellido: "Smirnov", dorsal: 29, equipo: "CZE", posicion: "Defensa" },
  { nombre: "Mathieu", apellido: "Fontaine", dorsal: 88, equipo: "BEL", posicion: "Defensa" },
  { nombre: "Hugo", apellido: "Müller", dorsal: 49, equipo: "ENG", posicion: "Delantero" },
  { nombre: "Takashi", apellido: "Fischer", dorsal: 21, equipo: "SUI", posicion: "Portero" },
  { nombre: "Joon-ho", apellido: "Schulz", dorsal: 6, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Miguel", apellido: "Saito", dorsal: 63, equipo: "GRE", posicion: "Portero" },
  { nombre: "Seo-jun", apellido: "Vincent", dorsal: 67, equipo: "NED", posicion: "Defensa" },
  { nombre: "Marek", apellido: "Kowalczyk", dorsal: 12, equipo: "TUR", posicion: "Defensa" },
  { nombre: "Jack", apellido: "Jung", dorsal: 47, equipo: "NOR", posicion: "Defensa" },
  { nombre: "Ignacio", apellido: "García", dorsal: 15, equipo: "TUR", posicion: "Delantero" },
  { nombre: "Kofi", apellido: "Boateng", dorsal: 6, equipo: "IRL", posicion: "Delantero" },
  { nombre: "Davide", apellido: "Chavez", dorsal: 93, equipo: "DEN", posicion: "Portero" },
  { nombre: "Rodrigo", apellido: "Larsson", dorsal: 66, equipo: "UAE", posicion: "Delantero" },
  { nombre: "Juan", apellido: "Faure", dorsal: 42, equipo: "CRO", posicion: "Portero" },
  { nombre: "Nicolas", apellido: "Gutierrez", dorsal: 69, equipo: "ARG", posicion: "Portero" },
  { nombre: "George", apellido: "Wilson", dorsal: 88, equipo: "KSA", posicion: "Portero" },
  { nombre: "Harry", apellido: "Ivanov", dorsal: 83, equipo: "BEL", posicion: "Defensa" },
  { nombre: "Gabriel", apellido: "Jung", dorsal: 5, equipo: "URU", posicion: "Portero" },
  { nombre: "Miguel", apellido: "Appiah", dorsal: 72, equipo: "BEL", posicion: "Defensa" },
  { nombre: "Ibrahim", apellido: "Sokolov", dorsal: 81, equipo: "PAN", posicion: "Delantero" },
  { nombre: "Min-jun", apellido: "Müller Ortiz", dorsal: 1, equipo: "NED", posicion: "Portero" },
  { nombre: "Pablo", apellido: "Arslan", dorsal: 14, equipo: "NOR", posicion: "Centrocampista" },
  { nombre: "Matteo", apellido: "Sidorov", dorsal: 49, equipo: "CRC", posicion: "Portero" },
  { nombre: "Ali", apellido: "Thomas", dorsal: 18, equipo: "CRC", posicion: "Centrocampista" },
  { nombre: "Leon", apellido: "Larsson", dorsal: 2, equipo: "MAR", posicion: "Portero" },
  { nombre: "Carlos", apellido: "Kowalski Gutierrez", dorsal: 71, equipo: "CRO", posicion: "Centrocampista" },
  { nombre: "George", apellido: "Jang", dorsal: 28, equipo: "JAM", posicion: "Defensa" },
  { nombre: "Pierre", apellido: "Appiah", dorsal: 25, equipo: "CAN", posicion: "Defensa" },
  { nombre: "Miguel", apellido: "Fedorov", dorsal: 83, equipo: "BEL", posicion: "Centrocampista" },
  { nombre: "Sergio", apellido: "Smith", dorsal: 93, equipo: "CIV", posicion: "Centrocampista" },
  { nombre: "Anders", apellido: "Mensah Romano", dorsal: 37, equipo: "NED", posicion: "Defensa" },
  { nombre: "Seo-jun", apellido: "Jung", dorsal: 79, equipo: "WAL", posicion: "Defensa" },
  { nombre: "Magnus", apellido: "Dabrowski", dorsal: 22, equipo: "ARG", posicion: "Centrocampista" },
  { nombre: "Samuel", apellido: "Ivanov", dorsal: 36, equipo: "ROU", posicion: "Defensa" },
  { nombre: "Joon-ho", apellido: "Fedorov", dorsal: 58, equipo: "GRE", posicion: "Centrocampista" },
  { nombre: "Hüseyin", apellido: "Bonnet", dorsal: 83, equipo: "CRO", posicion: "Centrocampista" },
  { nombre: "Paul", apellido: "Smith", dorsal: 34, equipo: "BEL", posicion: "Portero" },
  { nombre: "Martín", apellido: "Pérez", dorsal: 75, equipo: "PAN", posicion: "Defensa" },
  { nombre: "Ricardo", apellido: "Ramos", dorsal: 70, equipo: "NZL", posicion: "Defensa" },
  { nombre: "Magnus", apellido: "Yamamoto", dorsal: 18, equipo: "CHN", posicion: "Portero" },
  { nombre: "Jakub", apellido: "García", dorsal: 85, equipo: "PAR", posicion: "Defensa" },
  { nombre: "Cristian", apellido: "Dubois Fontaine", dorsal: 73, equipo: "MAR", posicion: "Delantero" },
  { nombre: "Anders", apellido: "Celik White", dorsal: 9, equipo: "AUT", posicion: "Centrocampista" },
  { nombre: "Ryan", apellido: "Brown Flores", dorsal: 47, equipo: "ISL", posicion: "Delantero" },
  { nombre: "Andrei", apellido: "Silva", dorsal: 84, equipo: "IRL", posicion: "Portero" },
  { nombre: "Esteban", apellido: "Suzuki", dorsal: 95, equipo: "AUT", posicion: "Defensa" },
  { nombre: "Oskar", apellido: "Nilsson", dorsal: 76, equipo: "BEL", posicion: "Centrocampista" },
  { nombre: "Oskar", apellido: "Roberts", dorsal: 67, equipo: "PAN", posicion: "Centrocampista" },
  { nombre: "Tae-yang", apellido: "Sahin", dorsal: 78, equipo: "ARG", posicion: "Defensa" },
  { nombre: "Alexei", apellido: "Carvalho", dorsal: 66, equipo: "SWE", posicion: "Defensa" },
  { nombre: "Erik", apellido: "Karlsson", dorsal: 78, equipo: "JPN", posicion: "Defensa" },
  { nombre: "Marek", apellido: "Greco", dorsal: 62, equipo: "RSA", posicion: "Delantero" },
  { nombre: "George", apellido: "Lewandowski", dorsal: 3, equipo: "VEN", posicion: "Portero" },
  { nombre: "Felix", apellido: "Lefebvre", dorsal: 18, equipo: "ENG", posicion: "Defensa" },
  { nombre: "Andrés", apellido: "Rousseau", dorsal: 67, equipo: "PAN", posicion: "Portero" },
  { nombre: "Kenji", apellido: "Evans", dorsal: 58, equipo: "NZL", posicion: "Delantero" },
  { nombre: "Louis", apellido: "Lewandowski", dorsal: 77, equipo: "MAR", posicion: "Defensa" },
  { nombre: "Alexis", apellido: "Yoon", dorsal: 59, equipo: "NED", posicion: "Defensa" },
  { nombre: "Oskar", apellido: "Ricci", dorsal: 3, equipo: "ALG", posicion: "Delantero" },
  { nombre: "Erik", apellido: "Fontaine", dorsal: 61, equipo: "GER", posicion: "Portero" },
  { nombre: "Alessandro", apellido: "Fischer", dorsal: 78, equipo: "ARG", posicion: "Delantero" },
  { nombre: "Esteban", apellido: "Santos", dorsal: 90, equipo: "KSA", posicion: "Defensa" },
  { nombre: "Hasan", apellido: "Persson", dorsal: 45, equipo: "MEX", posicion: "Delantero" },
  { nombre: "Jonas", apellido: "White", dorsal: 11, equipo: "DEN", posicion: "Delantero" },
  { nombre: "David", apellido: "Rodríguez", dorsal: 74, equipo: "JPN", posicion: "Portero" },
  { nombre: "Oskar", apellido: "Kim", dorsal: 53, equipo: "ROU", posicion: "Portero" },
  { nombre: "Niklas", apellido: "Appiah", dorsal: 34, equipo: "KSA", posicion: "Centrocampista" },
  { nombre: "Hiroshi", apellido: "Nowak", dorsal: 97, equipo: "COL", posicion: "Delantero" },
  { nombre: "Hasan", apellido: "Sahin", dorsal: 33, equipo: "WAL", posicion: "Centrocampista" },
  { nombre: "Jakub", apellido: "Müller", dorsal: 96, equipo: "ECU", posicion: "Delantero" },
  { nombre: "Pierre", apellido: "Alvarez Wojcik", dorsal: 44, equipo: "ITA", posicion: "Defensa" },
  { nombre: "Axel", apellido: "Rodríguez", dorsal: 12, equipo: "MAR", posicion: "Delantero" },
  { nombre: "Ivan", apellido: "Agyeman Thomas", dorsal: 48, equipo: "CRO", posicion: "Portero" },
  { nombre: "Viktor", apellido: "Wojcik", dorsal: 79, equipo: "DEN", posicion: "Portero" },
  { nombre: "Hugo", apellido: "Sidorov", dorsal: 2, equipo: "ALG", posicion: "Centrocampista" },
  { nombre: "Mathieu", apellido: "Alvarez Flores", dorsal: 90, equipo: "ECU", posicion: "Defensa" },
  { nombre: "Ricardo", apellido: "González", dorsal: 21, equipo: "URU", posicion: "Centrocampista" },
  { nombre: "Michal", apellido: "Nowak", dorsal: 52, equipo: "ALG", posicion: "Portero" },
  { nombre: "Sergio", apellido: "Watanabe", dorsal: 93, equipo: "TUR", posicion: "Centrocampista" },
  { nombre: "Hiroshi", apellido: "Faure", dorsal: 59, equipo: "PAN", posicion: "Portero" },
  { nombre: "Ibrahim", apellido: "Dogan", dorsal: 14, equipo: "BEL", posicion: "Centrocampista" },
  { nombre: "Sung-min", apellido: "Torres", dorsal: 33, equipo: "SUI", posicion: "Delantero" },
  { nombre: "Oskar", apellido: "Boateng", dorsal: 97, equipo: "RUS", posicion: "Delantero" },
  { nombre: "Pavel", apellido: "Pérez", dorsal: 62, equipo: "CAN", posicion: "Centrocampista" },
  { nombre: "Sergio", apellido: "Thomas", dorsal: 87, equipo: "ECU", posicion: "Centrocampista" },
  { nombre: "Andrzej", apellido: "Flores", dorsal: 69, equipo: "BRA", posicion: "Centrocampista" },
  { nombre: "Samuel", apellido: "Wojcik", dorsal: 87, equipo: "RUS", posicion: "Portero" },
  { nombre: "Théo", apellido: "Andersson", dorsal: 28, equipo: "POL", posicion: "Defensa" },
  { nombre: "Julien", apellido: "Johnson", dorsal: 31, equipo: "PAR", posicion: "Centrocampista" },
  { nombre: "Harry", apellido: "Asante", dorsal: 80, equipo: "GRE", posicion: "Defensa" },
  { nombre: "Leonardo", apellido: "Rossi Aydin", dorsal: 79, equipo: "ARG", posicion: "Portero" },
  { nombre: "Hasan", apellido: "Kim", dorsal: 64, equipo: "SWE", posicion: "Delantero" },
  { nombre: "Enzo", apellido: "Alvarez", dorsal: 36, equipo: "CRC", posicion: "Defensa" },
  { nombre: "Felix", apellido: "Wozniak Demir", dorsal: 70, equipo: "GER", posicion: "Centrocampista" },
  { nombre: "Piotr", apellido: "Bonnet", dorsal: 59, equipo: "JPN", posicion: "Delantero" },
  { nombre: "Min-jun", apellido: "Fernández", dorsal: 87, equipo: "COL", posicion: "Delantero" },
  { nombre: "Antonio", apellido: "Adjei", dorsal: 24, equipo: "AUT", posicion: "Defensa" },
  { nombre: "Ahmed", apellido: "Yoon", dorsal: 47, equipo: "TUN", posicion: "Delantero" },
  { nombre: "Wojciech", apellido: "Larsson", dorsal: 47, equipo: "PAN", posicion: "Centrocampista" },
  { nombre: "Nikolai", apellido: "Fischer", dorsal: 74, equipo: "ECU", posicion: "Portero" },
  { nombre: "Youssef", apellido: "Petrov", dorsal: 49, equipo: "ALG", posicion: "Defensa" },
  { nombre: "Erik", apellido: "García", dorsal: 23, equipo: "HON", posicion: "Delantero" },
  { nombre: "Jonas", apellido: "Flores", dorsal: 69, equipo: "SCO", posicion: "Delantero" },
  { nombre: "Haruto", apellido: "Oliveira", dorsal: 51, equipo: "MEX", posicion: "Defensa" },
  { nombre: "Alejandro", apellido: "Osei", dorsal: 61, equipo: "MEX", posicion: "Delantero" },
  { nombre: "Hyun-woo", apellido: "Karlsson", dorsal: 72, equipo: "SUI", posicion: "Centrocampista" },
  { nombre: "Nicolás", apellido: "Lim", dorsal: 87, equipo: "ALG", posicion: "Defensa" },
  { nombre: "Kenji", apellido: "Alvarez", dorsal: 63, equipo: "UAE", posicion: "Portero" },
  { nombre: "Emil", apellido: "Fedorov", dorsal: 81, equipo: "MAR", posicion: "Defensa" },
  { nombre: "Jae-hyun", apellido: "Kowalczyk", dorsal: 10, equipo: "CRO", posicion: "Defensa" },
  { nombre: "Sung-min", apellido: "Lee", dorsal: 84, equipo: "NOR", posicion: "Centrocampista" },
  { nombre: "Jakub", apellido: "Smirnov", dorsal: 47, equipo: "UAE", posicion: "Delantero" },
  { nombre: "Nicolas", apellido: "Martínez", dorsal: 17, equipo: "PAR", posicion: "Centrocampista" },
  { nombre: "Marco", apellido: "Nowak", dorsal: 14, equipo: "MEX", posicion: "Portero" },
  { nombre: "Ali", apellido: "Sánchez", dorsal: 99, equipo: "CRC", posicion: "Portero" },
  { nombre: "Giovanni", apellido: "Schulz", dorsal: 11, equipo: "ISL", posicion: "Centrocampista" },
  { nombre: "Daniel", apellido: "Watanabe", dorsal: 57, equipo: "KOR", posicion: "Defensa" },
  { nombre: "Felipe", apellido: "Pérez", dorsal: 5, equipo: "GRE", posicion: "Centrocampista" },
  { nombre: "Ali", apellido: "Chavez", dorsal: 35, equipo: "QAT", posicion: "Defensa" },
  { nombre: "Joaquín", apellido: "Popov", dorsal: 81, equipo: "IRN", posicion: "Centrocampista" },
  { nombre: "Tae-yang", apellido: "Walker", dorsal: 12, equipo: "QAT", posicion: "Centrocampista" },
  { nombre: "Magnus", apellido: "Schulz", dorsal: 39, equipo: "BRA", posicion: "Portero" },
  { nombre: "Esteban", apellido: "Weber", dorsal: 45, equipo: "DEN", posicion: "Delantero" },
  { nombre: "Tomás", apellido: "Yildiz Demir", dorsal: 39, equipo: "BRA", posicion: "Delantero" },
  { nombre: "Ryo", apellido: "Rodríguez", dorsal: 71, equipo: "CZE", posicion: "Defensa" },
  { nombre: "Andrzej", apellido: "Ivanov", dorsal: 51, equipo: "VEN", posicion: "Defensa" },
  { nombre: "Axel", apellido: "Thomas", dorsal: 34, equipo: "CRO", posicion: "Delantero" },
  { nombre: "Kofi", apellido: "Nkrumah", dorsal: 37, equipo: "POL", posicion: "Delantero" },
  { nombre: "Julien", apellido: "Rousseau", dorsal: 18, equipo: "NOR", posicion: "Portero" },
  { nombre: "Andrei", apellido: "Nkrumah", dorsal: 90, equipo: "CIV", posicion: "Defensa" },
  { nombre: "Do-yun", apellido: "Oliveira Ortiz", dorsal: 3, equipo: "TUN", posicion: "Portero" },
  { nombre: "Kenji", apellido: "Sidorov", dorsal: 94, equipo: "BRA", posicion: "Defensa" },
  { nombre: "Alessandro", apellido: "Aydin", dorsal: 28, equipo: "RUS", posicion: "Delantero" },
  { nombre: "Yuki", apellido: "Ozturk", dorsal: 48, equipo: "CHN", posicion: "Portero" },
  { nombre: "Joon-ho", apellido: "Becker Costa", dorsal: 35, equipo: "CRC", posicion: "Portero" },
  { nombre: "Emiliano", apellido: "Faure", dorsal: 33, equipo: "HUN", posicion: "Portero" },
  { nombre: "Lukas", apellido: "Asante", dorsal: 50, equipo: "QAT", posicion: "Defensa" },
  { nombre: "Fernando", apellido: "Bianchi", dorsal: 67, equipo: "COL", posicion: "Delantero" },
  { nombre: "Axel", apellido: "Yoshida", dorsal: 42, equipo: "GHA", posicion: "Portero" },
  { nombre: "Esteban", apellido: "Sahin Kobayashi", dorsal: 26, equipo: "ROU", posicion: "Portero" },
  { nombre: "Oliver", apellido: "Mensah", dorsal: 82, equipo: "IRN", posicion: "Centrocampista" },
  { nombre: "Diego", apellido: "Suzuki", dorsal: 75, equipo: "JPN", posicion: "Delantero" },
  { nombre: "Emmanuel", apellido: "Silva Kaya", dorsal: 89, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Matteo", apellido: "Ozturk", dorsal: 12, equipo: "RUS", posicion: "Portero" },
  { nombre: "Alejandro", apellido: "Schulz", dorsal: 90, equipo: "USA", posicion: "Defensa" },
  { nombre: "Hüseyin", apellido: "Jang", dorsal: 57, equipo: "EGY", posicion: "Portero" },
  { nombre: "Oskar", apellido: "Weber", dorsal: 33, equipo: "ENG", posicion: "Delantero" },
  { nombre: "Alexei", apellido: "Chavez", dorsal: 90, equipo: "CIV", posicion: "Defensa" },
  { nombre: "Antoine", apellido: "Park", dorsal: 94, equipo: "CHN", posicion: "Centrocampista" },
  { nombre: "Pierre", apellido: "Schulz Sokolov", dorsal: 38, equipo: "AUT", posicion: "Centrocampista" },
  { nombre: "Andrei", apellido: "Dogan Persson", dorsal: 94, equipo: "TUN", posicion: "Portero" },
  { nombre: "Magnus", apellido: "Owusu", dorsal: 42, equipo: "NED", posicion: "Delantero" },
  { nombre: "Julien", apellido: "Ozturk", dorsal: 99, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Do-yun", apellido: "Park", dorsal: 15, equipo: "MEX", posicion: "Portero" },
  { nombre: "Juan", apellido: "Fischer", dorsal: 23, equipo: "GER", posicion: "Defensa" },
  { nombre: "Leonardo", apellido: "Romano", dorsal: 5, equipo: "ISL", posicion: "Delantero" },
  { nombre: "Felipe", apellido: "Osei", dorsal: 7, equipo: "ROU", posicion: "Defensa" },
  { nombre: "Pablo", apellido: "Taylor Yildiz", dorsal: 11, equipo: "CHN", posicion: "Portero" },
  { nombre: "Bjorn", apellido: "Zielinski", dorsal: 48, equipo: "POR", posicion: "Centrocampista" },
  { nombre: "Ignacio", apellido: "Ribeiro Saito", dorsal: 10, equipo: "CHI", posicion: "Portero" },
  { nombre: "Antonio", apellido: "Ortiz", dorsal: 50, equipo: "EGY", posicion: "Defensa" },
  { nombre: "Felipe", apellido: "Fontaine", dorsal: 72, equipo: "HON", posicion: "Portero" },
  { nombre: "Anders", apellido: "Dabrowski", dorsal: 14, equipo: "NGA", posicion: "Defensa" },
  { nombre: "Michal", apellido: "Dubois", dorsal: 69, equipo: "QAT", posicion: "Centrocampista" },
  { nombre: "Min-jun", apellido: "Choi", dorsal: 48, equipo: "JAM", posicion: "Delantero" },
  { nombre: "Do-yun", apellido: "Ramos", dorsal: 28, equipo: "HUN", posicion: "Centrocampista" },
  { nombre: "Bjorn", apellido: "Volkov", dorsal: 51, equipo: "ARG", posicion: "Portero" },
  { nombre: "Kenji", apellido: "Flores", dorsal: 18, equipo: "SRB", posicion: "Portero" },
  { nombre: "Haruto", apellido: "Wilson", dorsal: 41, equipo: "ESP", posicion: "Centrocampista" },
  { nombre: "Alexis", apellido: "Schulz", dorsal: 13, equipo: "GER", posicion: "Delantero" },
  { nombre: "Anders", apellido: "Agyeman", dorsal: 47, equipo: "VEN", posicion: "Defensa" },
  { nombre: "David", apellido: "Esposito", dorsal: 74, equipo: "PAN", posicion: "Defensa" },
  { nombre: "Daniel", apellido: "Sahin", dorsal: 23, equipo: "CIV", posicion: "Portero" },
  { nombre: "Haruto", apellido: "Persson Rossi", dorsal: 8, equipo: "UKR", posicion: "Centrocampista" },
  { nombre: "Ivan", apellido: "Müller", dorsal: 99, equipo: "ECU", posicion: "Portero" },
  { nombre: "Emil", apellido: "Vargas Silva", dorsal: 41, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Cem", apellido: "Schulz", dorsal: 7, equipo: "CRC", posicion: "Delantero" },
  { nombre: "Onur", apellido: "Petrov Yamamoto", dorsal: 51, equipo: "MAR", posicion: "Defensa" },
  { nombre: "Jae-hyun", apellido: "Oliveira Wojcik", dorsal: 34, equipo: "CRO", posicion: "Delantero" },
  { nombre: "Cem", apellido: "Fischer", dorsal: 98, equipo: "AUS", posicion: "Delantero" },
  { nombre: "James", apellido: "Smith", dorsal: 72, equipo: "VEN", posicion: "Defensa" },
  { nombre: "Pablo", apellido: "Petrov", dorsal: 42, equipo: "URU", posicion: "Portero" },
  { nombre: "Andrzej", apellido: "Lim", dorsal: 25, equipo: "IRL", posicion: "Centrocampista" },
  { nombre: "Gabriel", apellido: "Girard", dorsal: 45, equipo: "QAT", posicion: "Defensa" },
  { nombre: "Alexei", apellido: "White Johnson", dorsal: 88, equipo: "CZE", posicion: "Defensa" },
  { nombre: "Luca", apellido: "Souza Boateng", dorsal: 80, equipo: "MAR", posicion: "Centrocampista" },
  { nombre: "Diego", apellido: "Marino", dorsal: 40, equipo: "UAE", posicion: "Delantero" },
  { nombre: "Nicolás", apellido: "Gutierrez", dorsal: 28, equipo: "COL", posicion: "Centrocampista" },
  { nombre: "Hasan", apellido: "Wagner", dorsal: 89, equipo: "ESP", posicion: "Delantero" },
  { nombre: "Felipe", apellido: "Girard Pereira", dorsal: 37, equipo: "ALG", posicion: "Centrocampista" },
  { nombre: "Miguel", apellido: "García", dorsal: 9, equipo: "ISL", posicion: "Centrocampista" },
  { nombre: "Bjorn", apellido: "López", dorsal: 38, equipo: "ISL", posicion: "Defensa" },
  { nombre: "Emil", apellido: "Romano", dorsal: 41, equipo: "CIV", posicion: "Portero" },
  { nombre: "Antoine", apellido: "Kuznetsov", dorsal: 72, equipo: "ESP", posicion: "Portero" },
  { nombre: "Samuel", apellido: "Kato", dorsal: 43, equipo: "CIV", posicion: "Delantero" },
  { nombre: "Jean", apellido: "Andersson Andersson", dorsal: 81, equipo: "SRB", posicion: "Defensa" },
  { nombre: "Cem", apellido: "Pereira", dorsal: 81, equipo: "SUI", posicion: "Delantero" },
  { nombre: "Rafael", apellido: "Tanaka", dorsal: 29, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Piotr", apellido: "Ferrari", dorsal: 94, equipo: "HUN", posicion: "Defensa" },
  { nombre: "Marek", apellido: "Schulz", dorsal: 55, equipo: "WAL", posicion: "Centrocampista" },
  { nombre: "Vladimir", apellido: "Brown", dorsal: 84, equipo: "AUS", posicion: "Defensa" },
  { nombre: "Paul", apellido: "Vargas", dorsal: 18, equipo: "IRN", posicion: "Defensa" },
  { nombre: "Jean", apellido: "Ortiz", dorsal: 93, equipo: "JPN", posicion: "Defensa" },
  { nombre: "Seo-jun", apellido: "Becker", dorsal: 94, equipo: "FRA", posicion: "Centrocampista" },
  { nombre: "Andrzej", apellido: "Saito", dorsal: 57, equipo: "SWE", posicion: "Defensa" },
  { nombre: "Julien", apellido: "Vincent Sánchez", dorsal: 98, equipo: "POL", posicion: "Defensa" },
  { nombre: "Ryan", apellido: "Sánchez", dorsal: 46, equipo: "CRO", posicion: "Delantero" },
  { nombre: "Jonas", apellido: "Yilmaz", dorsal: 92, equipo: "CZE", posicion: "Defensa" },
  { nombre: "Axel", apellido: "Meyer", dorsal: 21, equipo: "EGY", posicion: "Defensa" },
  { nombre: "Fernando", apellido: "Fernández", dorsal: 35, equipo: "JAM", posicion: "Defensa" },
  { nombre: "William", apellido: "Almeida", dorsal: 23, equipo: "QAT", posicion: "Delantero" },
  { nombre: "Ji-ho", apellido: "Asante", dorsal: 55, equipo: "PAN", posicion: "Portero" },
  { nombre: "Emil", apellido: "Kowalski", dorsal: 79, equipo: "GER", posicion: "Portero" },
  { nombre: "Nikolai", apellido: "Silva", dorsal: 32, equipo: "CRC", posicion: "Portero" },
  { nombre: "Axel", apellido: "Oliveira", dorsal: 25, equipo: "NOR", posicion: "Delantero" },
  { nombre: "Jakub", apellido: "Ito", dorsal: 60, equipo: "NGA", posicion: "Delantero" },
  { nombre: "Sora", apellido: "Souza", dorsal: 89, equipo: "MAR", posicion: "Delantero" },
  { nombre: "Nikolai", apellido: "Arslan Marino", dorsal: 24, equipo: "AUS", posicion: "Delantero" },
  { nombre: "Andrzej", apellido: "Sánchez", dorsal: 23, equipo: "IRQ", posicion: "Defensa" },
  { nombre: "Andrei", apellido: "Park Lefebvre", dorsal: 92, equipo: "JPN", posicion: "Portero" },
  { nombre: "Davide", apellido: "Karlsson", dorsal: 11, equipo: "ISL", posicion: "Defensa" },
  { nombre: "Oskar", apellido: "Santos", dorsal: 99, equipo: "NGA", posicion: "Centrocampista" },
  { nombre: "Erik", apellido: "Becker", dorsal: 23, equipo: "ITA", posicion: "Delantero" },
  { nombre: "Sota", apellido: "Volkov", dorsal: 37, equipo: "TUN", posicion: "Portero" },
  { nombre: "Maximilian", apellido: "González", dorsal: 80, equipo: "SUI", posicion: "Portero" },
  { nombre: "Pavel", apellido: "Ozturk", dorsal: 70, equipo: "ARG", posicion: "Delantero" },
  { nombre: "Kwame", apellido: "Kaya", dorsal: 59, equipo: "JAM", posicion: "Delantero" },
  { nombre: "Marco", apellido: "Rodríguez", dorsal: 32, equipo: "SWE", posicion: "Defensa" },
  { nombre: "Pedro", apellido: "Costa", dorsal: 84, equipo: "TUR", posicion: "Portero" },
  { nombre: "Finn", apellido: "Kobayashi", dorsal: 43, equipo: "URU", posicion: "Portero" },
  { nombre: "Leonardo", apellido: "Fontaine", dorsal: 21, equipo: "DEN", posicion: "Defensa" },
  { nombre: "Andrei", apellido: "Karlsson", dorsal: 5, equipo: "URU", posicion: "Centrocampista" },
  { nombre: "Do-yun", apellido: "Persson", dorsal: 9, equipo: "KSA", posicion: "Portero" },
  { nombre: "Ryo", apellido: "Schmidt", dorsal: 89, equipo: "SWE", posicion: "Centrocampista" },
  { nombre: "Felipe", apellido: "Taylor", dorsal: 90, equipo: "COL", posicion: "Portero" },
  { nombre: "Leonardo", apellido: "Castro", dorsal: 12, equipo: "RSA", posicion: "Centrocampista" },
  { nombre: "Grzegorz", apellido: "Lee", dorsal: 34, equipo: "GRE", posicion: "Defensa" },
  { nombre: "Serkan", apellido: "Ozturk", dorsal: 64, equipo: "TUN", posicion: "Defensa" },
  { nombre: "Ryo", apellido: "González", dorsal: 16, equipo: "FRA", posicion: "Delantero" },
  { nombre: "Thomas", apellido: "Taylor", dorsal: 79, equipo: "HON", posicion: "Delantero" },
  { nombre: "Juan", apellido: "Wilson", dorsal: 2, equipo: "ALG", posicion: "Centrocampista" },
  { nombre: "David", apellido: "Kato", dorsal: 39, equipo: "IRL", posicion: "Portero" },
  { nombre: "Davide", apellido: "Yoon", dorsal: 51, equipo: "FRA", posicion: "Defensa" },
  { nombre: "Mathieu", apellido: "Cho", dorsal: 87, equipo: "RSA", posicion: "Delantero" },
  { nombre: "Ricardo", apellido: "Sahin", dorsal: 20, equipo: "IRQ", posicion: "Centrocampista" },
  { nombre: "Oleg", apellido: "Lewandowski", dorsal: 96, equipo: "POR", posicion: "Centrocampista" },
  { nombre: "Min-jun", apellido: "López", dorsal: 27, equipo: "UKR", posicion: "Centrocampista" },
  { nombre: "Javier", apellido: "Tanaka", dorsal: 4, equipo: "RUS", posicion: "Delantero" },
  { nombre: "Tomás", apellido: "Gustafsson", dorsal: 24, equipo: "CAN", posicion: "Centrocampista" },
  { nombre: "Min-jun", apellido: "Nkrumah", dorsal: 53, equipo: "URU", posicion: "Delantero" },
  { nombre: "Kwame", apellido: "Saito", dorsal: 28, equipo: "SRB", posicion: "Defensa" },
  { nombre: "Simone", apellido: "Díaz", dorsal: 26, equipo: "URU", posicion: "Delantero" },
  { nombre: "Onur", apellido: "Sahin Arslan", dorsal: 20, equipo: "EGY", posicion: "Centrocampista" },
  { nombre: "Hasan", apellido: "Vargas", dorsal: 40, equipo: "IRL", posicion: "Defensa" },
  { nombre: "Antonio", apellido: "Flores", dorsal: 87, equipo: "KOR", posicion: "Defensa" },
  { nombre: "Ricardo", apellido: "Rivera", dorsal: 15, equipo: "ARG", posicion: "Centrocampista" },
  { nombre: "Juan", apellido: "Ferrari", dorsal: 43, equipo: "CHN", posicion: "Portero" },
  { nombre: "Giovanni", apellido: "Yoshida", dorsal: 3, equipo: "WAL", posicion: "Defensa" },
  { nombre: "Do-yun", apellido: "Ito", dorsal: 36, equipo: "SCO", posicion: "Delantero" },
  { nombre: "Thomas", apellido: "Dubois", dorsal: 36, equipo: "CAN", posicion: "Portero" },
  { nombre: "Cristian", apellido: "Chavez Lim", dorsal: 71, equipo: "SCO", posicion: "Centrocampista" },
  { nombre: "Leon", apellido: "Watanabe", dorsal: 74, equipo: "VEN", posicion: "Defensa" },
  { nombre: "Pablo", apellido: "Cho", dorsal: 70, equipo: "QAT", posicion: "Portero" },
  { nombre: "Maximilian", apellido: "Oliveira Ricci", dorsal: 50, equipo: "ITA", posicion: "Portero" },
  { nombre: "Grzegorz", apellido: "Volkov", dorsal: 79, equipo: "GRE", posicion: "Centrocampista" },
  { nombre: "Hyun-woo", apellido: "Ortiz", dorsal: 11, equipo: "CHN", posicion: "Defensa" },
  { nombre: "Alessandro", apellido: "Morozov", dorsal: 13, equipo: "IRQ", posicion: "Centrocampista" },
  { nombre: "Boris", apellido: "Roberts", dorsal: 19, equipo: "AUT", posicion: "Centrocampista" },
  { nombre: "Piotr", apellido: "Jung", dorsal: 42, equipo: "IRQ", posicion: "Delantero" },
  { nombre: "Rafael", apellido: "Marino Lim", dorsal: 62, equipo: "CHN", posicion: "Defensa" },
  { nombre: "Kenji", apellido: "Schneider", dorsal: 66, equipo: "USA", posicion: "Delantero" },
  { nombre: "Leonardo", apellido: "Ribeiro", dorsal: 39, equipo: "CHN", posicion: "Delantero" },
  { nombre: "Andrzej", apellido: "Boateng", dorsal: 71, equipo: "GHA", posicion: "Delantero" },
  { nombre: "Viktor", apellido: "Taylor Petrov", dorsal: 56, equipo: "RUS", posicion: "Defensa" },
  { nombre: "Hugo", apellido: "Carvalho", dorsal: 95, equipo: "CIV", posicion: "Portero" },
  { nombre: "Oleg", apellido: "Bianchi", dorsal: 57, equipo: "CMR", posicion: "Centrocampista" },
  { nombre: "Tomasz", apellido: "Ricci Persson", dorsal: 42, equipo: "COD", posicion: "Portero" },
  { nombre: "Alessandro", apellido: "Meyer", dorsal: 75, equipo: "ARG", posicion: "Defensa" },
  { nombre: "Erik", apellido: "Yamamoto", dorsal: 50, equipo: "UAE", posicion: "Defensa" },
  { nombre: "Harry", apellido: "Lee", dorsal: 39, equipo: "SRB", posicion: "Delantero" },
  { nombre: "Tae-yang", apellido: "García", dorsal: 79, equipo: "PAN", posicion: "Defensa" },
  { nombre: "Sora", apellido: "Souza González", dorsal: 91, equipo: "GRE", posicion: "Portero" },
  { nombre: "Kenji", apellido: "Mensah", dorsal: 56, equipo: "CRC", posicion: "Centrocampista" },
  { nombre: "Emil", apellido: "Ivanov", dorsal: 70, equipo: "CHI", posicion: "Defensa" },
  { nombre: "Ali", apellido: "Svensson Karlsson", dorsal: 54, equipo: "SEN", posicion: "Centrocampista" },
  { nombre: "Felix", apellido: "Ribeiro López", dorsal: 19, equipo: "CIV", posicion: "Delantero" },
  { nombre: "Jonas", apellido: "Zielinski Popov", dorsal: 90, equipo: "KSA", posicion: "Defensa" },
  { nombre: "Andrei", apellido: "Sokolov", dorsal: 50, equipo: "GRE", posicion: "Defensa" },
  { nombre: "Antoine", apellido: "Rodríguez", dorsal: 74, equipo: "COD", posicion: "Defensa" },
  { nombre: "Cem", apellido: "Ramos", dorsal: 74, equipo: "ROU", posicion: "Portero" },
  { nombre: "Ricardo", apellido: "Eriksson", dorsal: 15, equipo: "RSA", posicion: "Portero" },
  { nombre: "Leon", apellido: "Vargas", dorsal: 97, equipo: "SWE", posicion: "Delantero" },
  { nombre: "Rodrigo", apellido: "Ferrari Boateng", dorsal: 61, equipo: "BEL", posicion: "Centrocampista" },
  { nombre: "Miguel", apellido: "Ortiz", dorsal: 2, equipo: "NZL", posicion: "Delantero" },
  { nombre: "Cristian", apellido: "Jung", dorsal: 54, equipo: "GRE", posicion: "Centrocampista" },
  { nombre: "Ryo", apellido: "Saito", dorsal: 94, equipo: "AUT", posicion: "Portero" },
  { nombre: "Ali", apellido: "Souza", dorsal: 85, equipo: "NOR", posicion: "Portero" },
  { nombre: "Yuto", apellido: "Schneider", dorsal: 65, equipo: "BEL", posicion: "Centrocampista" },
  { nombre: "Joseph", apellido: "Tanaka Suzuki", dorsal: 33, equipo: "BRA", posicion: "Portero" },
  { nombre: "Hugo", apellido: "Hoffmann", dorsal: 85, equipo: "UAE", posicion: "Centrocampista" },
  { nombre: "Hugo", apellido: "Mensah", dorsal: 63, equipo: "TUN", posicion: "Portero" },
  { nombre: "Sung-min", apellido: "Becker", dorsal: 77, equipo: "SEN", posicion: "Delantero" },
  { nombre: "Andrzej", apellido: "Mensah", dorsal: 85, equipo: "QAT", posicion: "Defensa" },
  { nombre: "George", apellido: "Jang", dorsal: 7, equipo: "AUT", posicion: "Portero" },
  { nombre: "Miguel", apellido: "Wojcik", dorsal: 61, equipo: "SRB", posicion: "Delantero" },
  { nombre: "Tomás", apellido: "Gustafsson", dorsal: 61, equipo: "AUT", posicion: "Defensa" },
  { nombre: "Ignacio", apellido: "Fernández", dorsal: 37, equipo: "UAE", posicion: "Delantero" },
  { nombre: "Min-jun", apellido: "Silva", dorsal: 13, equipo: "GRE", posicion: "Delantero" },
  { nombre: "Youssef", apellido: "Darko", dorsal: 13, equipo: "SUI", posicion: "Delantero" },
  { nombre: "Oleg", apellido: "Owusu", dorsal: 94, equipo: "EGY", posicion: "Centrocampista" },
  { nombre: "Enzo", apellido: "García", dorsal: 87, equipo: "BRA", posicion: "Portero" },
  { nombre: "Diego", apellido: "Vargas", dorsal: 14, equipo: "UAE", posicion: "Centrocampista" },
  { nombre: "Charlie", apellido: "Appiah", dorsal: 25, equipo: "GER", posicion: "Portero" },
  { nombre: "Alessandro", apellido: "Evans Schmidt", dorsal: 91, equipo: "JPN", posicion: "Portero" },
  { nombre: "Maximilian", apellido: "Vincent", dorsal: 15, equipo: "TUN", posicion: "Centrocampista" },
  { nombre: "Sora", apellido: "Carvalho", dorsal: 82, equipo: "IRQ", posicion: "Centrocampista" },
  { nombre: "Grzegorz", apellido: "Park", dorsal: 33, equipo: "GHA", posicion: "Portero" },
  { nombre: "Hiroshi", apellido: "Persson", dorsal: 50, equipo: "UKR", posicion: "Portero" },
  { nombre: "Ibrahim", apellido: "Agyeman", dorsal: 23, equipo: "QAT", posicion: "Portero" },
  { nombre: "Emre", apellido: "Johnson", dorsal: 79, equipo: "CRC", posicion: "Defensa" },
  { nombre: "Emre", apellido: "Chavez Petrov", dorsal: 28, equipo: "USA", posicion: "Delantero" },
  { nombre: "Ibrahim", apellido: "Ribeiro Ribeiro", dorsal: 74, equipo: "SUI", posicion: "Delantero" },
  { nombre: "Martín", apellido: "Hoffmann", dorsal: 84, equipo: "ARG", posicion: "Portero" },
  { nombre: "Axel", apellido: "Jung", dorsal: 51, equipo: "ARG", posicion: "Delantero" },
  { nombre: "Mustafa", apellido: "Ferreira", dorsal: 70, equipo: "PER", posicion: "Portero" },
  { nombre: "Viktor", apellido: "Sahin", dorsal: 16, equipo: "GRE", posicion: "Centrocampista" },
  { nombre: "Ren", apellido: "Esposito", dorsal: 47, equipo: "RUS", posicion: "Portero" },
  { nombre: "Pavel", apellido: "Yamamoto", dorsal: 83, equipo: "ALG", posicion: "Defensa" },
  { nombre: "Carlos", apellido: "Muller", dorsal: 39, equipo: "ISL", posicion: "Portero" },
  { nombre: "Anders", apellido: "Sidorov", dorsal: 95, equipo: "EGY", posicion: "Defensa" },
  { nombre: "Ricardo", apellido: "Owusu", dorsal: 63, equipo: "ISL", posicion: "Portero" },
  { nombre: "Joaquín", apellido: "Ozturk", dorsal: 69, equipo: "UAE", posicion: "Portero" },
  { nombre: "Ricardo", apellido: "Cho", dorsal: 93, equipo: "ENG", posicion: "Delantero" },
  { nombre: "Thomas", apellido: "Rivera", dorsal: 59, equipo: "SEN", posicion: "Defensa" },
  { nombre: "Pablo", apellido: "Wagner Yildiz", dorsal: 84, equipo: "ESP", posicion: "Delantero" },
  { nombre: "Juan", apellido: "Fischer", dorsal: 2, equipo: "CMR", posicion: "Portero" },
  { nombre: "Sota", apellido: "Bianchi", dorsal: 59, equipo: "NGA", posicion: "Portero" },
  { nombre: "Leonardo", apellido: "Thomas Almeida", dorsal: 26, equipo: "KSA", posicion: "Centrocampista" },
  { nombre: "Michal", apellido: "Ramos", dorsal: 18, equipo: "IRL", posicion: "Defensa" },
  { nombre: "Juan", apellido: "Kang", dorsal: 9, equipo: "JPN", posicion: "Centrocampista" },
  { nombre: "Leon", apellido: "Girard", dorsal: 90, equipo: "CZE", posicion: "Defensa" },
  { nombre: "Alexei", apellido: "Silva", dorsal: 18, equipo: "MEX", posicion: "Delantero" },
  { nombre: "Jean", apellido: "Celik Rossi", dorsal: 1, equipo: "ARG", posicion: "Defensa" },
  { nombre: "Matteo", apellido: "Watanabe", dorsal: 54, equipo: "NZL", posicion: "Defensa" },
  { nombre: "Harry", apellido: "Nkrumah Rivera", dorsal: 58, equipo: "JAM", posicion: "Defensa" },
  { nombre: "Hugo", apellido: "Díaz", dorsal: 77, equipo: "TUN", posicion: "Delantero" },
  { nombre: "Matteo", apellido: "Saito", dorsal: 45, equipo: "HON", posicion: "Portero" },
  { nombre: "Kwame", apellido: "Castro", dorsal: 13, equipo: "ROU", posicion: "Defensa" },
  { nombre: "Oleg", apellido: "Taylor", dorsal: 36, equipo: "ITA", posicion: "Defensa" },
  { nombre: "Simone", apellido: "Kaya", dorsal: 64, equipo: "CMR", posicion: "Defensa" },
  { nombre: "Juan", apellido: "Nilsson Watanabe", dorsal: 27, equipo: "IRN", posicion: "Centrocampista" },
  { nombre: "Hyun-woo", apellido: "Popov", dorsal: 6, equipo: "USA", posicion: "Portero" },
  { nombre: "Vicente", apellido: "Pérez", dorsal: 63, equipo: "CAN", posicion: "Portero" },
  { nombre: "Kwame", apellido: "Choi", dorsal: 54, equipo: "ALG", posicion: "Centrocampista" },
  { nombre: "Daniel", apellido: "Choi", dorsal: 30, equipo: "MEX", posicion: "Defensa" },
  { nombre: "Andrzej", apellido: "Olsson", dorsal: 29, equipo: "BEL", posicion: "Delantero" },
  { nombre: "Hüseyin", apellido: "Ivanov Becker", dorsal: 28, equipo: "IRQ", posicion: "Defensa" },
  { nombre: "Axel", apellido: "Kuznetsov", dorsal: 93, equipo: "EGY", posicion: "Centrocampista" }
]);


// operaciones de actualización, eliminación e inserción RF9

db.equipos.updateOne(
    { nombre: "República Democrática del Congo", codigo: "COD" },
    { $set: { nombre: "República Democrática de Congo", codigo: "COD" } }
);

db.equipos.deleteOne({
    nombre: "República Democrática del Congo",
    codigo: "COD"
});

db.equipos.insertOne({
    nombre: "República Democrática del Congo",
    codigo: "COD"
});

// operaciones de busqueda RF10
db.equipos.findOne({
    codigo: "ARG"
});

// operaciones de filtrado RF10
db.jugadores.find({
    equipo: "ARG"
});

db.jugadores.find({
    posicion: "Portero"
});

db.jugadores.find({
    dorsal: {
        $gte: 1,
        $lte: 5
    }
});

// ordenamiento

db.jugadores.find().sort({
    apellido: 1 // ordenar alfabeticamente por apellido, de la A a la Z
});

// paginacion - limitar maximo 20 docs
db.jugadores.find()
    .sort({ apellido: 1 })
    .skip(0)
    .limit(20);